MeterLogger: user/cgiwifi.h File Reference
cgiwifi.h File Reference
#include "httpd.h"
Functions
int cgiWiFiScan (HttpdConnData *connData)
void tplSetup (HttpdConnData *connData, char *token, void **arg)
int cgiWiFi (HttpdConnData *connData)
int cgiSetup (HttpdConnData *connData)
int cgiWifiSetMode (HttpdConnData *connData)
void cgiWifiInit ()
Function Documentation
cgiSetup()
int cgiSetup (HttpdConnData * connData)
Definition at line 187 of file cgiwifi.c.
References cfg_save(), HttpdConnData::conn, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), INFO, kw_to_w_str(), syscfg_t::mqtt_host, NULL, os_strncpy, os_timer_arm, os_timer_disarm, os_timer_setfn, HttpdConnData::postBuff, resetTimer, resetTimerCb(), syscfg_t::sta_pwd, syscfg_t::sta_ssid, and sys_cfg.
{
     char essid[128];
     char passwd[128];
     char mqtthost[64];
 #ifdef IMPULSE
     char impulse_meter_serial[32 + 1];
     char impulse_meter_units_string[32 + 1];
     char impulse_meter_units[32 + 1];
     char impulses_per_unit[8 + 1];
 #endif
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     httpdFindArg(connData->postBuff, "essid", essid, sizeof(essid));
     httpdFindArg(connData->postBuff, "passwd", passwd, sizeof(passwd));
     httpdFindArg(connData->postBuff, "mqtthost", mqtthost, sizeof(mqtthost));
 #ifdef IMPULSE
     httpdFindArg(connData->postBuff, "impulse_meter_serial", impulse_meter_serial, sizeof(impulse_meter_serial));
     httpdFindArg(connData->postBuff, "impulse_meter_units", impulse_meter_units_string, sizeof(impulse_meter_units_string));
     httpdFindArg(connData->postBuff, "impulses_per_unit", impulses_per_unit, sizeof(impulses_per_unit));
 #endif
     os_strncpy((char*)sys_cfg.sta_ssid, essid, 32);
     os_strncpy((char*)sys_cfg.sta_pwd, passwd, 64);
     os_strncpy((char*)sys_cfg.mqtt_host, mqtthost, 64);
 #ifdef IMPULSE
     os_strncpy((char*)sys_cfg.impulse_meter_serial, impulse_meter_serial, 32 + 1);
     kw_to_w_str(impulse_meter_units_string, impulse_meter_units);
     os_strncpy((char*)sys_cfg.impulse_meter_units, impulse_meter_units, 32 + 1);
     os_strncpy((char*)sys_cfg.impulses_per_unit, impulses_per_unit, 8 + 1);
     sys_cfg.impulse_meter_count = 0;
 #endif
     cfg_save(NULL, NULL);
     INFO("Try to connect to AP %s pw %s\n", essid, passwd);
 #ifdef IMPULSE
     httpdRedirect(connData, "impulse_meter_setting_up.html");
 #else
     httpdRedirect(connData, "setting_up.html");
 #endif
     // restart to go directly to sample mode after 5 seconds
     os_timer_disarm(&resetTimer);
     os_timer_setfn(&resetTimer, resetTimerCb, NULL);
     os_timer_arm(&resetTimer, 5000, 0);
     return HTTPD_CGI_DONE;
 }
cgiWiFi()
int cgiWiFi (HttpdConnData * connData)
cgiWifiInit()
void cgiWifiInit ()
Definition at line 317 of file cgiwifi.c.
References memset, and wifiStartScan().
Referenced by httpdInit().
{
     memset(&cgiWifiAps, 0, sizeof(ScanResultData));
     wifiStartScan();
 }
cgiWiFiScan()
int cgiWiFiScan (HttpdConnData * connData)
Definition at line 110 of file cgiwifi.c.
References ScanResultData::apData, ApData::enc, HTTPD_CGI_DONE, HTTPD_CGI_SERVER_ERROR, httpdEndHeaders(), httpdHeader(), httpdSend(), httpdStartResponse(), ScanResultData::noAps, NULL, ApData::rssi, ScanResultData::scanInProgress, ApData::ssid, tfp_snprintf(), and wifiStartScan().
{
     int len;
     int i;
     char buff[1024];
     httpdStartResponse(connData, 200);
     httpdHeader(connData, "Content-Type", "text/json");
     httpdEndHeaders(connData);
     if (cgiWifiAps.scanInProgress==1) {
         //We're still scanning. Tell Javascript code that.
         len = tfp_snprintf(buff, 1024, "{\n \"result\": { \n\"inProgress\": \"1\"\n }\n}\n");
         if (httpdSend(connData, buff, len) == 0) {
             return HTTPD_CGI_SERVER_ERROR;
         }
     } else {
         //We have a scan result. Pass it on.
         len = tfp_snprintf(buff, 1024, "{\n \"result\": { \n\"inProgress\": \"0\", \n\"APs\": [\n");
         if (httpdSend(connData, buff, len) == 0) {
             return HTTPD_CGI_SERVER_ERROR;
         }
         if (cgiWifiAps.apData==NULL) cgiWifiAps.noAps=0;
         for (i=0; i<cgiWifiAps.noAps; i++) {
             //Fill in json code for an access point
             len = tfp_snprintf(buff, 1024, "{\"essid\": \"%s\", \"rssi\": \"%d\", \"enc\": \"%d\"}%s\n",
                     cgiWifiAps.apData[i]->ssid, cgiWifiAps.apData[i]->rssi,
                     cgiWifiAps.apData[i]->enc, (i==cgiWifiAps.noAps-1)?"":",");
             if (httpdSend(connData, buff, len) == 0) {
                 return HTTPD_CGI_SERVER_ERROR;
             }
         }
         len = tfp_snprintf(buff, 1024, "]\n}\n}\n");
         if (httpdSend(connData, buff, len) == 0) {
             return HTTPD_CGI_SERVER_ERROR;
         }
         //Also start a new scan.
         wifiStartScan();
     }
     return HTTPD_CGI_DONE;
 }
cgiWifiSetMode()
int cgiWifiSetMode (HttpdConnData * connData)
Definition at line 243 of file cgiwifi.c.
References HttpdConnData::conn, HttpdConnData::getArgs, HTTPD_CGI_DONE, httpdFindArg(), httpdRedirect(), INFO, NULL, system_restart(), and wifi_set_opmode().
{
     int len;
     char buff[1024];
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     len=httpdFindArg(connData->getArgs, "mode", buff, sizeof(buff));
     if (len!=0) {
         INFO("cgiWifiSetMode: %s\n", buff);
 #ifndef DEMO_MODE
         wifi_set_opmode(atoi(buff));
         system_restart();
 #endif
     }
     httpdRedirect(connData, "/wifi");
     return HTTPD_CGI_DONE;
 }
tplSetup()
void tplSetup (HttpdConnData * connData, char * token, void ** arg)
Definition at line 265 of file cgiwifi.c.
References cfg_load(), divide_str_by_1000(), httpdSend(), syscfg_t::mqtt_host, NULL, os_strcmp, os_strcpy, syscfg_t::sta_pwd, syscfg_t::sta_ssid, sys_cfg, tfp_snprintf(), and wifi_get_opmode().
{
     char buff[1024];
 #ifdef IMPULSE
     char impulse_meter_units[32 + 1];
 #endif // IMPULSE
     int x;
     //static struct station_config stconf;
     if (token==NULL) return;
     //wifi_station_get_config(&stconf);
     cfg_load();
     os_strcpy(buff, "Unknown");
     if (os_strcmp(token, "WiFiMode")==0) {
         x=wifi_get_opmode();
         if (x == 1) os_strcpy(buff, "Client");
         if (x == 2) os_strcpy(buff, "SoftAP");
         if (x == 3) os_strcpy(buff, "STA+AP");
     }
     else if (os_strcmp(token, "currSsid") == 0) {
         os_strcpy(buff, (char*)sys_cfg.sta_ssid);
     }
     else if (os_strcmp(token, "WiFiPasswd") == 0) {
         os_strcpy(buff, (char*)sys_cfg.sta_pwd);
     }
     else if (os_strcmp(token, "WiFiapwarn") == 0) {
         x = wifi_get_opmode();
         if (x == 2) {
             os_strcpy(buff, "<b>Can't scan in this mode.</b> Click <a href=\"setmode.cgi?mode=3\">here</a> to go to STA+AP mode.");
         }
         else {
             os_strcpy(buff, "Click <a href=\"setmode.cgi?mode=2\">here</a> to go to standalone AP mode.");
         }
     }
     else if (os_strcmp(token, "MqttHost") == 0) {
         os_strcpy(buff, (char*)sys_cfg.mqtt_host);
     }
 #ifdef IMPULSE
     else if (os_strcmp(token, "ImpulseMeterSerial") == 0) {
         os_strcpy(buff, (char*)sys_cfg.impulse_meter_serial);
     }
     else if (os_strcmp(token, "ImpulseMeterUnits") == 0) {
         tfp_snprintf(impulse_meter_units, 32 + 1, "%u", atoi(sys_cfg.impulse_meter_units) + sys_cfg.impulse_meter_count * (1000 / atoi(sys_cfg.impulses_per_unit)));
         divide_str_by_1000(impulse_meter_units, buff);
     }
     else if (os_strcmp(token, "ImpulsesPerUnit") == 0) {
         os_strcpy(buff, (char*)sys_cfg.impulses_per_unit);
     }
 #endif
     httpdSend(connData, buff, -1);
 }