MeterLogger: modules/config.c File Reference
config.c File Reference
#include <stddef.h>
#include <esp8266.h>
#include "mqtt.h"
#include "config.h"
#include "user_config.h"
#include "debug.h"
#include "utils.h"
#include "tinyprintf.h"
#include "driver/ext_spi_flash.h"
Macros
#define EXT_CFG_LOCATION 0x0
#define EXT_SPI_RAM_SEC_SIZE 0x200
#define SAVE_DEFER_TIME 2000
Functions
bool ICACHE_FLASH_ATTR cfg_save (uint16_t *calculated_crc, uint16_t *saved_crc)
void ICACHE_FLASH_ATTR cfg_load ()
void ICACHE_FLASH_ATTR cfg_save_defered ()
bool ICACHE_FLASH_ATTR cfg_save_ssid_pwd (char *ssid_pwd, uint16_t *calculated_crc, uint16_t *saved_crc)
ICACHE_FLASH_ATTR void config_save_timer_func (void *arg)
Variables
syscfg_t sys_cfg
SAVE_FLAG saveFlag
static os_timer_t config_save_timer
char config_save_timer_running
Macro Definition Documentation
EXT_CFG_LOCATION
#define EXT_CFG_LOCATION 0x0
Definition at line 15 of file config.c.
Referenced by cfg_load(), and cfg_save().
EXT_SPI_RAM_SEC_SIZE
#define EXT_SPI_RAM_SEC_SIZE 0x200
Definition at line 20 of file config.c.
Referenced by cfg_load(), and cfg_save().
SAVE_DEFER_TIME
#define SAVE_DEFER_TIME 2000
Definition at line 23 of file config.c.
Referenced by cfg_save_defered(), and config_save_timer_func().
Function Documentation
cfg_load()
void ICACHE_FLASH_ATTR cfg_load ()
Definition at line 88 of file config.c.
References ccit_crc16(), syscfg_t::ccit_crc16, CFG_LOCATION, cfg_save(), DEFAULT_METER_SERIAL, DEFAULT_SECURITY, EXT_CFG_LOCATION, ext_spi_flash_read(), EXT_SPI_RAM_SEC_SIZE, ICACHE_FLASH_ATTR, INFO, key, memcpy, memset, METER_SERIAL_LEN, MQTT_CLIENT_ID, MQTT_HOST, MQTT_KEEPALIVE, MQTT_PASS, MQTT_PORT, MQTT_USER, NULL, os_memset, printf, STA_PASS, STA_SSID, STA_TYPE, system_get_chip_id(), system_param_load(), and tfp_snprintf().
Referenced by cfg_save(), and tplSetup().
            {
     // DEBUG: we suppose nothing else is touching sys_cfg while saving otherwise checksum becomes wrong
     INFO("\r\nload ...\r\n");
 #if defined(IMPULSE) && !defined(DEBUG_NO_METER)    // use internal flash if built with DEBUG_NO_METER=1
     ext_spi_flash_read((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                    (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
     if (saveFlag.flag == 0) {
         ext_spi_flash_read((EXT_CFG_LOCATION + 0) * EXT_SPI_RAM_SEC_SIZE,
                        (uint32 *)&sys_cfg, sizeof(syscfg_t));
     } else {
         ext_spi_flash_read((EXT_CFG_LOCATION + 1) * EXT_SPI_RAM_SEC_SIZE,
                        (uint32 *)&sys_cfg, sizeof(syscfg_t));
     }
 #else
     system_param_load(CFG_LOCATION, 0, &sys_cfg, sizeof(syscfg_t));
 #endif  // IMPULSE
     // if checksum fails...
     if (sys_cfg.ccit_crc16 != ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder))) {
 #ifdef DEBUG
         printf("config crc error, default conf loaded\n");
 #endif // DEBUG
         // if first time config load default conf
         os_memset(&sys_cfg, 0x00, sizeof(syscfg_t));
         tfp_snprintf(sys_cfg.sta_ssid, 64, "%s", STA_SSID);
         tfp_snprintf(sys_cfg.sta_pwd, 64, "%s", STA_PASS);
         sys_cfg.sta_type = STA_TYPE;
         sys_cfg.ap_enabled = true;
         tfp_snprintf(sys_cfg.device_id, 16, MQTT_CLIENT_ID, system_get_chip_id());
         tfp_snprintf(sys_cfg.mqtt_host, 64, "%s", MQTT_HOST);
         sys_cfg.mqtt_port = MQTT_PORT;
         tfp_snprintf(sys_cfg.mqtt_user, 32, "%s", MQTT_USER);
         tfp_snprintf(sys_cfg.mqtt_pass, 32, "%s", MQTT_PASS);
         sys_cfg.security = DEFAULT_SECURITY;    //default non ssl
         memcpy(sys_cfg.key, key, sizeof(key));
         sys_cfg.mqtt_keepalive = MQTT_KEEPALIVE;
 #ifdef IMPULSE
         tfp_snprintf(sys_cfg.impulse_meter_serial, METER_SERIAL_LEN, DEFAULT_METER_SERIAL);
         tfp_snprintf(sys_cfg.impulse_meter_units, 2, "0");
         tfp_snprintf(sys_cfg.impulses_per_unit, 4, "100");
         sys_cfg.impulse_meter_count = 0;
         sys_cfg.operating_time = 0;
 #else
         sys_cfg.ac_thermo_state = 0;
         sys_cfg.offline_close_at = 0;
 #ifndef NO_CRON
         memset(&sys_cfg.cron_jobs, 0, sizeof(cron_job_t));
 #endif  // NO_CRON
 #endif  // IMPULSE
         INFO(" default configuration\r\n");
         cfg_save(NULL, NULL);
     }
     else {
 #ifdef DEBUG
         printf("config crc ok\n");
 #endif // DEBUG
     }
 }
cfg_save()
bool ICACHE_FLASH_ATTR cfg_save (uint16_t * calculated_crc, uint16_t * saved_crc)
Definition at line 28 of file config.c.
References ccit_crc16(), syscfg_t::ccit_crc16, cfg_load(), CFG_LOCATION, EXT_CFG_LOCATION, ext_spi_flash_erase_sector(), ext_spi_flash_read(), ext_spi_flash_write(), EXT_SPI_RAM_SEC_SIZE, ICACHE_FLASH_ATTR, and system_param_save_with_protect().
Referenced by cfg_load(), cfg_save_ssid_pwd(), cgiSetup(), config_save_timer_func(), minute_timer_func(), mqtt_rpc_open_until(), mqtt_rpc_open_until_delta(), mqtt_rpc_set_pwd(), mqtt_rpc_set_ssid(), mqtt_rpc_start_ap(), and mqtt_rpc_stop_ap().
{
 #ifdef IMPULSE
     uint32_t impulse_meter_count_temp;
 #endif // IMPULSE
 #if defined(IMPULSE) && !defined(DEBUG_NO_METER)    // use internal flash if built with DEBUG_NO_METER=1
     do {
         // try to save until sys_cfg.impulse_meter_count does not change
         impulse_meter_count_temp = sys_cfg.impulse_meter_count;
         // calculate checksum on sys_cfg struct without ccit_crc16
         sys_cfg.ccit_crc16 = ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder));
         ext_spi_flash_read((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                            (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         if (saveFlag.flag == 0) {
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 1);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 1) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&sys_cfg, sizeof(syscfg_t));
             saveFlag.flag = 1;
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 2);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         } else {
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 0);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 0) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&sys_cfg, sizeof(syscfg_t));
             saveFlag.flag = 0;
 #ifdef EXT_SPI_RAM_IS_NAND
             ext_spi_flash_erase_sector(EXT_CFG_LOCATION + 2);
 #endif  // EXT_SPI_RAM_IS_NAND
             ext_spi_flash_write((EXT_CFG_LOCATION + 2) * EXT_SPI_RAM_SEC_SIZE,
                             (uint32 *)&saveFlag, sizeof(SAVE_FLAG));
         }
     } while (sys_cfg.impulse_meter_count != impulse_meter_count_temp);
 #else
     // calculate checksum on sys_cfg struct without ccit_crc16
     sys_cfg.ccit_crc16 = ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder));
     system_param_save_with_protect(CFG_LOCATION, &sys_cfg, sizeof(syscfg_t));
     // check for flash memory error
     if (calculated_crc && saved_crc) {  // check if return values was requested
         *saved_crc = sys_cfg.ccit_crc16;
         cfg_load(); // reload saved config
         *calculated_crc = ccit_crc16(0xffff, (uint8_t *)&sys_cfg, offsetof(syscfg_t, ccit_crc16) - offsetof(syscfg_t, cfg_holder));
         if (*calculated_crc != *saved_crc) {
             return false;
         }
     }
 #endif  // IMPULSE
     return true;
 }
cfg_save_defered()
void ICACHE_FLASH_ATTR cfg_save_defered ()
Definition at line 154 of file config.c.
References config_save_timer, config_save_timer_func(), NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and SAVE_DEFER_TIME.
Referenced by ac_thermo_close(), ac_thermo_open(), add_cron_job_from_query(), and clear_cron_jobs().
                    {
     os_timer_disarm(&config_save_timer);
     os_timer_setfn(&config_save_timer, (os_timer_func_t *)config_save_timer_func, NULL);
     os_timer_arm(&config_save_timer, SAVE_DEFER_TIME, 0);
 }
cfg_save_ssid_pwd()
bool ICACHE_FLASH_ATTR cfg_save_ssid_pwd (char * ssid_pwd, uint16_t * calculated_crc, uint16_t * saved_crc)
Definition at line 160 of file config.c.
References cfg_save(), COMMAND_PARAMS_L, ICACHE_FLASH_ATTR, memset, MQTT_MESSAGE_L, NULL, printf, query_string_unescape(), syscfg_t::sta_pwd, syscfg_t::sta_ssid, strncmp, and strncpy.
Referenced by minute_timer_func(), and mqtt_rpc_set_ssid_pwd().
{
     // for parsing query string formatted parameters
     char *str;
     char *query_string_key, *query_string_value;
     char query_string_key_value[MQTT_MESSAGE_L];
     char *context_query_string, *context_key_value;
     char ssid_pwd_copy[COMMAND_PARAMS_L];
     strncpy(ssid_pwd_copy, ssid_pwd, COMMAND_PARAMS_L); // make a copy since strtok_r() changes it
     str = strtok_r(ssid_pwd_copy, "&", &context_query_string);
     while (str != NULL) {
         strncpy(query_string_key_value, str, MQTT_MESSAGE_L);
         query_string_key = strtok_r(query_string_key_value, "=", &context_key_value);
         query_string_value = strtok_r(NULL, "=", &context_key_value);
         if (strncmp(query_string_key, "ssid", MQTT_MESSAGE_L) == 0) {
             // un-escape & and =
             query_string_unescape(query_string_value);
             // change sta_ssid, save if different
 #ifdef DEBUG
             printf("key: %s value: %s\n", query_string_key, query_string_value);
 #endif  // DEBUG
             if (strncmp(sys_cfg.sta_ssid, query_string_value, 32 - 1) != 0) {
                 memset(sys_cfg.sta_ssid, 0, sizeof(sys_cfg.sta_ssid));
                 strncpy(sys_cfg.sta_ssid, query_string_value, 32 - 1);
             }
         }
         else if (strncmp(query_string_key, "pwd", MQTT_MESSAGE_L) == 0) {
             // change sta_pwd, save if different
             if (query_string_value == 0) {
                 // there is no value - no password used, use null string
 #ifdef DEBUG
                 printf("key: %s value: %s\n", query_string_key, "null");
 #endif  // DEBUG
                 if (strncmp(sys_cfg.sta_pwd, "", 1) != 0) {
                     memset(sys_cfg.sta_pwd, 0, sizeof(sys_cfg.sta_pwd));
                     strncpy(sys_cfg.sta_pwd, "", 1);
                 }
             }
             else {
                 // un-escape & and =
                 query_string_unescape(query_string_value);
 #ifdef DEBUG
                 printf("key: %s value: %s\n", query_string_key, query_string_value);
 #endif  // DEBUG
                 if (strncmp(sys_cfg.sta_pwd, query_string_value, 64 - 1) != 0) {
                     memset(sys_cfg.sta_pwd, 0, sizeof(sys_cfg.sta_pwd));
                     strncpy(sys_cfg.sta_pwd, query_string_value, 64 - 1);
                 }
             }
         }
         str = strtok_r(NULL, "&", &context_query_string);
     }
     return cfg_save(calculated_crc, saved_crc);
 }
config_save_timer_func()
ICACHE_FLASH_ATTR void config_save_timer_func (void * arg)
Definition at line 219 of file config.c.
References cfg_save(), config_save_timer, config_save_timer_func(), config_save_timer_running, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and SAVE_DEFER_TIME.
Referenced by cfg_save_defered(), and config_save_timer_func().
{
     if (config_save_timer_running) {
         // reschedule
         os_timer_disarm(&config_save_timer);
         os_timer_setfn(&config_save_timer, (os_timer_func_t *)config_save_timer_func, NULL);
         os_timer_arm(&config_save_timer, SAVE_DEFER_TIME, 0);
     }
     else {
         // stop timer
         os_timer_disarm(&config_save_timer);
         config_save_timer_running = 0;
         cfg_save(NULL, NULL);
     }
 }
Variable Documentation
config_save_timer
os_timer_t config_save_timer static
Definition at line 24 of file config.c.
Referenced by cfg_save_defered(), and config_save_timer_func().
config_save_timer_running
char config_save_timer_running
Definition at line 25 of file config.c.
Referenced by config_save_timer_func().
saveFlag
SAVE_FLAG saveFlag
Definition at line 13 of file config.c.
sys_cfg
syscfg_t sys_cfg
Definition at line 12 of file config.c.
Referenced by ac_thermo_close(), ac_thermo_open(), add_cron_job_from_query(), cgiSetup(), clear_cron_jobs(), cron_destroy(), cron_init(), minute_timer_func(), mqtt_rpc_ap_status(), mqtt_rpc_clear_cron(), mqtt_rpc_cron(), mqtt_rpc_crypto(), mqtt_rpc_mem(), mqtt_rpc_open_until(), mqtt_rpc_open_until_delta(), mqtt_rpc_ping(), mqtt_rpc_reset_reason(), mqtt_rpc_restart(), mqtt_rpc_rssi(), mqtt_rpc_set_cron(), mqtt_rpc_set_pwd(), mqtt_rpc_set_ssid(), mqtt_rpc_set_ssid_pwd(), mqtt_rpc_ssid(), mqtt_rpc_start_ap(), mqtt_rpc_status(), mqtt_rpc_stop_ap(), mqtt_rpc_uptime(), mqtt_rpc_vdd(), mqtt_rpc_version(), mqtt_rpc_wifi_status(), tplSetup(), wifi_connect(), wifi_default(), wifi_fallback(), wifi_handle_event_cb(), wifi_reconnect_timer_func(), wifi_scan_done_cb(), and wifi_scan_result_cb_unregister().