MeterLogger: user/cron/cron.h File Reference
cron.h File Reference
Data Structures
struct cron_job_t
struct cron_jobs_t
Macros
#define TOPIC_L 64
#define MESSAGE_L 100
#define FUNCTIONNAME_L 32
#define KEY_VALUE_L 64
#define COMMAND_L 32
#define COMMAND_PARAMS_L 96
#define CRON_JOBS_MAX 16
#define CRON_FIELD_L 8
Typedefs
typedef cron_job_t cron_job_list_t[CRON_JOBS_MAX]
Functions
ICACHE_FLASH_ATTR void cron_init ()
ICACHE_FLASH_ATTR unsigned int add_cron_job_from_query (char *query)
ICACHE_FLASH_ATTR void clear_cron_jobs ()
ICACHE_FLASH_ATTR void cron_destroy ()
Macro Definition Documentation
COMMAND_L
#define COMMAND_L 32
Definition at line 5 of file cron.h.
Referenced by add_cron_job_from_query(), and minute_timer_func().
COMMAND_PARAMS_L
#define COMMAND_PARAMS_L 96
Definition at line 6 of file cron.h.
Referenced by add_cron_job_from_query(), and cfg_save_ssid_pwd().
CRON_FIELD_L
#define CRON_FIELD_L 8
Definition at line 9 of file cron.h.
Referenced by add_cron_job_from_query(), and minute_timer_func().
CRON_JOBS_MAX
#define CRON_JOBS_MAX 16
Definition at line 8 of file cron.h.
Referenced by add_cron_job_from_query().
FUNCTIONNAME_L
#define FUNCTIONNAME_L 32
Definition at line 3 of file cron.h.
KEY_VALUE_L
#define KEY_VALUE_L 64
Definition at line 4 of file cron.h.
Referenced by add_cron_job_from_query().
MESSAGE_L
#define MESSAGE_L 100
Definition at line 2 of file cron.h.
TOPIC_L
#define TOPIC_L 64
Definition at line 1 of file cron.h.
Typedef Documentation
cron_job_list_t
typedef cron_job_t cron_job_list_t[CRON_JOBS_MAX]
Definition at line 28 of file cron.h.
Function Documentation
add_cron_job_from_query()
ICACHE_FLASH_ATTR unsigned int add_cron_job_from_query (char * query)
Definition at line 285 of file cron.c.
References cfg_save_defered(), COMMAND_L, COMMAND_PARAMS_L, CRON_FIELD_L, cron_jobs_t::cron_job_list, syscfg_t::cron_jobs, CRON_JOBS_MAX, ICACHE_FLASH_ATTR, key, KEY_VALUE_L, memcpy, memset, MQTT_MESSAGE_L, cron_jobs_t::n, NULL, os_printf, strlen, strncmp, strncpy, strstr, and sys_cfg.
Referenced by mqtt_rpc_set_cron().
{
     char cron_params[MQTT_MESSAGE_L];
     char *str;
     char *key, *value;
     char key_value[KEY_VALUE_L];
     char command_params[COMMAND_PARAMS_L];
     char *context_query_string, *context_key_value;
     strncpy(cron_params, query, MQTT_MESSAGE_L);    // work with a copy
     command_params[0] = 0;  // set zero length
     if (sys_cfg.cron_jobs.n <= CRON_JOBS_MAX - 1) {     // if there are room for more cron jobs
         memset(&sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n], 0, sizeof(cron_job_t));
         str = strstr(cron_params, "command=") + 8;                      // get string after command=
         if (str != NULL) {
             str = strtok_r(str, "=", &context_query_string);        // get function name
             if (str != NULL) {
                 str = strtok_r(NULL, "", &context_query_string);    // get paramters to function
                 if (str != NULL) {
                     strncpy(command_params, str, COMMAND_PARAMS_L);
                     memcpy(cron_params + (str - cron_params), "\0", 1);         // truncate cron_params after function
                 }
             }
         }
         // parse mqtt message for query string
         str = strtok_r(cron_params, "&", &context_query_string);
         while (str != NULL) {
             strncpy(key_value, str, KEY_VALUE_L);
             key = strtok_r(key_value, "=", &context_key_value);
             value = strtok_r(NULL, "=", &context_key_value);
             if (strncmp(key, "minute", KEY_VALUE_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].minute, value, CRON_FIELD_L);
             }
             else if (strncmp(key, "hour", KEY_VALUE_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].hour, value, CRON_FIELD_L);
             }
             else if (strncmp(key, "day_of_month", KEY_VALUE_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].day_of_month, value, CRON_FIELD_L);
             }
             else if (strncmp(key, "month", KEY_VALUE_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].month, value, CRON_FIELD_L);
             }
             else if (strncmp(key, "day_of_week", KEY_VALUE_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].day_of_week, value, CRON_FIELD_L);
             }
             else if (strncmp(key, "command", COMMAND_L) == 0) {
                 strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].command, value, COMMAND_L);
 #ifdef DEBUG
                 os_printf("command: %s\n\r", sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].command);
 #endif
                 if (strlen(command_params)) {
                     strncpy(sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].command_params, command_params, COMMAND_PARAMS_L);
 #ifdef DEBUG
                     os_printf("command_params: %s\n\r", sys_cfg.cron_jobs.cron_job_list[sys_cfg.cron_jobs.n].command_params);
 #endif
                 }
                 sys_cfg.cron_jobs.n++;
 #ifdef DEBUG
                 os_printf("job #%d added\n\r", sys_cfg.cron_jobs.n);
 #endif
             }
             str = strtok_r(NULL, "&", &context_query_string);
         }
         // save it to flash
         cfg_save_defered();
     }
     return sys_cfg.cron_jobs.n;
 }
clear_cron_jobs()
ICACHE_FLASH_ATTR void clear_cron_jobs ()
Definition at line 359 of file cron.c.
References cfg_save_defered(), syscfg_t::cron_jobs, ICACHE_FLASH_ATTR, memset, os_printf, and sys_cfg.
Referenced by minute_timer_func(), and mqtt_rpc_clear_cron().
{
 #ifdef DEBUG
     //debug_cron_jobs();
 #endif
     memset(&sys_cfg.cron_jobs, 0, sizeof(cron_job_t));
     // save it to flash
     cfg_save_defered();
 #ifdef DEBUG
     os_printf("\n\rcleared all jobs\n\r");
 #endif
 }
cron_destroy()
ICACHE_FLASH_ATTR void cron_destroy ()
Definition at line 373 of file cron.c.
References cron_jobs_t::cron_job_list, syscfg_t::cron_jobs, ICACHE_FLASH_ATTR, minute_timer, cron_jobs_t::n, os_printf, os_timer_disarm, and sys_cfg.
Referenced by system_restart_defered().
                     {
     os_timer_disarm(&minute_timer);
 }
cron_init()
ICACHE_FLASH_ATTR void cron_init ()
Definition at line 271 of file cron.c.
References syscfg_t::cron_jobs, ICACHE_FLASH_ATTR, minute_timer, minute_timer_func(), cron_jobs_t::n, NULL, os_printf, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and sys_cfg.
                  {
     //memset(&sys_cfg.cron_jobs, 0, sizeof(cron_job_t));
     // check if there are any cron jobs to run every minute
     os_timer_disarm(&minute_timer);
     os_timer_setfn(&minute_timer, (os_timer_func_t *)minute_timer_func, NULL);
     os_timer_arm(&minute_timer, 60000, 1);
 #ifdef DEBUG
     os_printf("\n\rcron jobs: %d\n\r", sys_cfg.cron_jobs.n);
 #endif
 }