MeterLogger: esp-open-lwip/include/lwip/app/dhcpserver.h File Reference
dhcpserver.h File Reference
#include "dhcpserver_common.h"
Macros
#define dhcps_router_enabled(offer) ((offer & OFFER_ROUTER) != 0)
#define DHCPS_DEBUG 0
#define DHCPS_LEASE_TIMER dhcps_lease_time
Functions
void dhcps_start (struct ip_info *info)
void dhcps_stop (void)
void dhcps_set_DNS (struct ip_addr *dns_ip) ICACHE_FLASH_ATTR
struct dhcps_pool * dhcps_get_mapping (uint16_t no) ICACHE_FLASH_ATTR
void dhcps_set_mapping (struct ip_addr *addr, uint8 *mac, uint32 lease_time) ICACHE_FLASH_ATTR
Variables
uint32 dhcps_lease_time
Macro Definition Documentation
DHCPS_DEBUG
#define DHCPS_DEBUG 0
Definition at line 6 of file dhcpserver.h.
DHCPS_LEASE_TIMER
#define DHCPS_LEASE_TIMER dhcps_lease_time
Definition at line 9 of file dhcpserver.h.
Referenced by add_offer_options(), and parse_msg().
dhcps_router_enabled
#define dhcps_router_enabled (offer) ((offer & OFFER_ROUTER) != 0)
Definition at line 4 of file dhcpserver.h.
Referenced by add_offer_options().
Function Documentation
dhcps_get_mapping()
struct dhcps_pool* dhcps_get_mapping (uint16_t no)
Definition at line 1144 of file dhcpserver.c.
References NULL, _list_node::pnext, and _list_node::pnode.
{
         list_node *pback_node = NULL;
         for(pback_node = plist; pback_node != NULL; pback_node = pback_node->pnext, no--) {
                 if(no == 0) return pback_node->pnode;
         }
         return NULL;
 }
dhcps_set_DNS()
void dhcps_set_DNS (struct ip_addr * dns_ip)
Definition at line 1140 of file dhcpserver.c.
References dns_ip.
Referenced by wifi_softap_ip_config().
{
         dns_address = *dns_ip;
 }
dhcps_set_mapping()
void dhcps_set_mapping (struct ip_addr * addr, uint8 * mac, uint32 lease_time)
Definition at line 1153 of file dhcpserver.c.
References ip_addr::addr, dhcps_pool::ip, dhcps_pool::lease_timer, dhcps_pool::mac, node_insert_to_list(), NULL, os_memcpy, os_zalloc, _list_node::pnext, and _list_node::pnode.
{
         list_node *pback_node = NULL;
         list_node *pnode = NULL;
         struct dhcps_pool *pdhcps_pool = NULL;
         pdhcps_pool = (struct dhcps_pool *) os_zalloc(sizeof(struct dhcps_pool));
         pdhcps_pool->ip.addr = addr->addr;
         os_memcpy(pdhcps_pool->mac, mac, sizeof(pdhcps_pool->mac));
         pdhcps_pool->lease_timer = lease_time;
         pnode = (list_node *) os_zalloc(sizeof(list_node));
         pnode->pnode = pdhcps_pool;
         pnode->pnext = NULL;
         node_insert_to_list(&plist, pnode);
 }
dhcps_start()
void dhcps_start (struct ip_info * info)
Definition at line 880 of file dhcpserver.c.
References ip_addr::addr, broadcast_dhcps, client_address_plus, DHCPS_SERVER_PORT, eagle_lwip_getif(), handle_dhcp(), ip_info::ip, IP4_ADDR, NULL, os_printf, pcb_dhcps, server_address, dhcps_lease::start_ip, and wifi_softap_init_dhcps_lease().
{
         struct netif * apnetif = (struct netif *) eagle_lwip_getif(0x01);
         if(apnetif->dhcps_pcb != NULL) {
                 udp_remove(apnetif->dhcps_pcb);
         }
         pcb_dhcps = udp_new();
         if(pcb_dhcps == NULL || info == NULL) {
                 os_printf("dhcps_start(): could not obtain pcb\n");
         }
         apnetif->dhcps_pcb = pcb_dhcps;
         IP4_ADDR(&broadcast_dhcps, 255, 255, 255, 255);
         server_address = info->ip;
         if(dns_address.addr == 0) {
                 dns_address = server_address;
         }
         wifi_softap_init_dhcps_lease(server_address.addr);
         client_address_plus.addr = dhcps_lease.start_ip.addr;
         udp_bind(pcb_dhcps, &info->ip, DHCPS_SERVER_PORT);
         udp_recv(pcb_dhcps, handle_dhcp, NULL);
 #if DHCPS_DEBUG
         os_printf("dhcps:dhcps_start->udp_recv function Set a receive callback handle_dhcp for UDP_PCB pcb_dhcps\n");
 #endif
 }
dhcps_stop()
void dhcps_stop (void)
Definition at line 912 of file dhcpserver.c.
References eagle_lwip_getif(), node_remove_from_list(), NULL, os_free, pcb_dhcps, plist, _list_node::pnext, and _list_node::pnode.
{
         struct netif * apnetif = (struct netif *) eagle_lwip_getif(0x01);
         udp_disconnect(pcb_dhcps);
         //  dhcps_lease_flag = true;
         if(apnetif->dhcps_pcb != NULL) {
                 udp_remove(apnetif->dhcps_pcb);
                 apnetif->dhcps_pcb = NULL;
         }
         //udp_remove(pcb_dhcps);
         list_node *pnode = NULL;
         list_node *pback_node = NULL;
         pnode = plist;
         while(pnode != NULL) {
                 pback_node = pnode;
                 pnode = pback_node->pnext;
                 node_remove_from_list(&plist, pback_node);
                 os_free(pback_node->pnode);
                 pback_node->pnode = NULL;
                 os_free(pback_node);
                 pback_node = NULL;
         }
 }
Variable Documentation
dhcps_lease_time
uint32 dhcps_lease_time
Definition at line 36 of file dhcpserver.c.
Referenced by wifi_softap_get_dhcps_lease_time(), wifi_softap_reset_dhcps_lease_time(), and wifi_softap_set_dhcps_lease_time().