MeterLogger: esp-open-lwip/include/lwip/app/encdhcpserver.h File Reference
encdhcpserver.h File Reference
#include "dhcpserver_common.h"
Macros
#define enc_dhcps_router_enabled(offer) ((offer & OFFER_ROUTER) != 0)
#define enc_DHCPS_LEASE_TIMER enc_dhcps_lease_time
#define ENCDHCPS_DEBUG 0
Functions
void enc_dhcps_start (struct netif *enetif)
void enc_dhcps_stop (void)
void enc_dhcps_set_DNS (struct ip_addr *dns_ip) ICACHE_FLASH_ATTR
struct dhcps_pool * enc_dhcps_get_mapping (uint16_t no) ICACHE_FLASH_ATTR
void enc_dhcps_set_mapping (struct ip_addr *addr, uint8 *mac, uint32 lease_time) ICACHE_FLASH_ATTR
Variables
uint32 enc_dhcps_lease_time
Macro Definition Documentation
enc_DHCPS_LEASE_TIMER
#define enc_DHCPS_LEASE_TIMER enc_dhcps_lease_time
Definition at line 8 of file encdhcpserver.h.
Referenced by enc_add_offer_options(), and enc_parse_msg().
enc_dhcps_router_enabled
#define enc_dhcps_router_enabled (offer) ((offer & OFFER_ROUTER) != 0)
Definition at line 4 of file encdhcpserver.h.
Referenced by enc_add_offer_options().
ENCDHCPS_DEBUG
#define ENCDHCPS_DEBUG 0
Definition at line 9 of file encdhcpserver.h.
Function Documentation
enc_dhcps_get_mapping()
struct dhcps_pool* enc_dhcps_get_mapping (uint16_t no)
Definition at line 1005 of file encdhcpserver.c.
References NULL, _list_node::pnext, and _list_node::pnode.
{
         list_node *pback_node = NULL;
         for(pback_node = enc_plist; pback_node != NULL; pback_node = pback_node->pnext, no--) {
                 if(no == 0) return pback_node->pnode;
         }
         return NULL;
 }
enc_dhcps_set_DNS()
void enc_dhcps_set_DNS (struct ip_addr * dns_ip)
Definition at line 1001 of file encdhcpserver.c.
References dns_ip.
{
         enc_dns_address = *dns_ip;
 }
enc_dhcps_set_mapping()
void enc_dhcps_set_mapping (struct ip_addr * addr, uint8 * mac, uint32 lease_time)
Definition at line 1014 of file encdhcpserver.c.
References ip_addr::addr, dhcps_pool::ip, dhcps_pool::lease_timer, dhcps_pool::mac, node_insert_to_list(), NULL, os_memcpy, os_zalloc, _list_node::pnext, and _list_node::pnode.
{
         list_node *pback_node = NULL;
         list_node *pnode = NULL;
         struct dhcps_pool *pdhcps_pool = NULL;
         pdhcps_pool = (struct dhcps_pool *) os_zalloc(sizeof(struct dhcps_pool));
         pdhcps_pool->ip.addr = addr->addr;
         os_memcpy(pdhcps_pool->mac, mac, sizeof(pdhcps_pool->mac));
         pdhcps_pool->lease_timer = lease_time;
         pnode = (list_node *) os_zalloc(sizeof(list_node));
         pnode->pnode = pdhcps_pool;
         pnode->pnext = NULL;
         node_insert_to_list(&enc_plist, pnode);
 }
enc_dhcps_start()
void enc_dhcps_start (struct netif * enetif)
Definition at line 777 of file encdhcpserver.c.
References ip_addr::addr, DHCPS_SERVER_PORT, enc_broadcast_dhcps, enc_client_address_plus, enc_dhcp_server_running, enc_dhcps_lease, enc_handle_dhcp(), enc_pcb_dhcps, enc_server_address, enc_softap_init_dhcps_lease(), IP4_ADDR, netif::ip_addr, NULL, os_printf, and dhcps_lease::start_ip.
{
         if(enetif == NULL) {
                 // os_printf("encdhcps: dhcps_start(): enetif == NULL\n");
                 return;
         }
         if(enetif->dhcps_pcb != NULL) {
                 udp_remove(enetif->dhcps_pcb);
         }
         enc_pcb_dhcps = udp_new();
         if(enc_pcb_dhcps == NULL) {
                 // os_printf("encdhcps: dhcps_start(): could not obtain pcb\n");
                 return;
         }
         enetif->dhcps_pcb = enc_pcb_dhcps;
         IP4_ADDR(&enc_broadcast_dhcps, 255, 255, 255, 255);
         enc_server_address = enetif->ip_addr;
         if(enc_dns_address.addr == 0) {
                 enc_dns_address = enc_server_address;
         }
         enc_softap_init_dhcps_lease(enc_server_address.addr);
         enc_client_address_plus.addr = enc_dhcps_lease.start_ip.addr;
         udp_bind(enc_pcb_dhcps, &enetif->ip_addr, DHCPS_SERVER_PORT);
         udp_recv(enc_pcb_dhcps, enc_handle_dhcp, NULL);
 #if ENCDHCPS_DEBUG
         os_printf("encdhcps:dhcps_start->udp_recv function Set a receive callback handle_dhcp for UDP_PCB pcb_dhcps\n");
 #endif
         enc_dhcp_server_running = true;
 }
enc_dhcps_stop()
void enc_dhcps_stop (void)
Definition at line 813 of file encdhcpserver.c.
References ecnetif, enc_dhcp_server_running, enc_pcb_dhcps, enc_plist, node_remove_from_list(), NULL, os_free, _list_node::pnext, and _list_node::pnode.
{
         enc_dhcp_server_running = false;
         udp_disconnect(enc_pcb_dhcps);
         if(ecnetif.dhcps_pcb != NULL) {
                 udp_remove(ecnetif.dhcps_pcb);
                 ecnetif.dhcps_pcb = NULL;
         }
         list_node *pnode = NULL;
         list_node *pback_node = NULL;
         pnode = enc_plist;
         while(pnode != NULL) {
                 pback_node = pnode;
                 pnode = pback_node->pnext;
                 node_remove_from_list(&enc_plist, pback_node);
                 os_free(pback_node->pnode);
                 pback_node->pnode = NULL;
                 os_free(pback_node);
                 pback_node = NULL;
         }
 }
Variable Documentation
enc_dhcps_lease_time
uint32 enc_dhcps_lease_time
Definition at line 36 of file encdhcpserver.c.
Referenced by enc_softap_get_dhcps_lease_time(), enc_softap_reset_dhcps_lease_time(), and enc_softap_set_dhcps_lease_time().