MeterLogger: user/exception_handler.c File Reference
exception_handler.c File Reference
#include <esp8266.h>
#include "tinyprintf.h"
#include "exception_handler.h"
#include "xtensa/corebits.h"
#include "user_config.h"
Data Structures
struct stack_trace_context_t
Macros
#define STACK_TRACE_BUFFER_N 128
Functions
void _xtos_set_exception_handler (int cause, void(exhandler)(struct XTensa_exception_frame_s *frame))
void ets_wdt_disable ()
void ets_wdt_enable ()
void save_extra_sfrs_for_exception ()
static ICACHE_FLASH_ATTR unsigned int getaregval (int reg)
static ICACHE_FLASH_ATTR void print_stack (uint32_t start, uint32_t end)
static ICACHE_FLASH_ATTR void print_reason ()
static ICACHE_FLASH_ATTR void exception_handler (struct XTensa_exception_frame_s *frame)
ICACHE_FLASH_ATTR void exception_handler_init ()
ICACHE_FLASH_ATTR void stack_trace_append (char *c)
ICACHE_FLASH_ATTR void stack_trace_last ()
Variables
struct XTensa_exception_frame_s saved_regs
struct stack_trace_context_t stack_trace_context
char stack_trace_buffer [STACK_TRACE_BUFFER_N]
Macro Definition Documentation
STACK_TRACE_BUFFER_N
#define STACK_TRACE_BUFFER_N 128
Definition at line 8 of file exception_handler.c.
Referenced by exception_handler_init(), print_reason(), print_stack(), stack_trace_append(), and stack_trace_last().
Function Documentation
_xtos_set_exception_handler()
void _xtos_set_exception_handler (int cause, void(exhandler)(struct XTensa_exception_frame_s *frame))
Referenced by exception_handler_init().
ets_wdt_disable()
void ets_wdt_disable ()
Referenced by exception_handler().
ets_wdt_enable()
void ets_wdt_enable ()
Referenced by exception_handler().
exception_handler()
static ICACHE_FLASH_ATTR void exception_handler (struct XTensa_exception_frame_s * frame) static
Definition at line 141 of file exception_handler.c.
References XTensa_exception_frame_s::a1, ets_wdt_disable(), ets_wdt_enable(), ICACHE_FLASH_ATTR, memcpy, print_reason(), save_extra_sfrs_for_exception(), saved_regs, spi_flash_erase_sector(), SPI_FLASH_SEC_SIZE, STACK_TRACE_N, and STACK_TRACE_SEC.
Referenced by exception_handler_init().
{
     uint8_t i;
     // Save the extra registers the Xtensa HAL doesn't save
     save_extra_sfrs_for_exception();
     // Copy registers the Xtensa HAL did save to saved_regs
     memcpy(&saved_regs, frame, 19*4);
     // Credits go to Cesanta for this trick. A1 seems to be destroyed, but because it
     // has a fixed offset from the address of the passed frame, we can recover it.
     // saved_regs.a1 = (uint32_t)frame + EXCEPTION_GDB_SP_OFFSET;
     saved_regs.a1 = (uint32_t)frame + 0x100;
     ets_wdt_disable();
     for (i = 0; i * SPI_FLASH_SEC_SIZE < STACK_TRACE_N; i++) {
         spi_flash_erase_sector(STACK_TRACE_SEC + i);
     }
     print_reason();
     ets_wdt_enable();
     while(1) {
         // wait for watchdog to bite
     }
 }
exception_handler_init()
ICACHE_FLASH_ATTR void exception_handler_init ()
Definition at line 169 of file exception_handler.c.
References _xtos_set_exception_handler(), stack_trace_context_t::buffer, stack_trace_context_t::buffer_index, exception_handler(), stack_trace_context_t::flash_index, ICACHE_FLASH_ATTR, memset, stack_trace_buffer, STACK_TRACE_BUFFER_N, and stack_trace_context.
Referenced by mqtt_rpc_restart().
{
     unsigned int i;
     int exno[] = {EXCCAUSE_ILLEGAL, EXCCAUSE_INSTR_ERROR, EXCCAUSE_DIVIDE_BY_ZERO, EXCCAUSE_UNALIGNED,
                   EXCCAUSE_INSTR_DATA_ERROR, EXCCAUSE_LOAD_STORE_DATA_ERROR, EXCCAUSE_INSTR_ADDR_ERROR,
                   EXCCAUSE_LOAD_STORE_ADDR_ERROR, EXCCAUSE_INSTR_PROHIBITED, EXCCAUSE_LOAD_PROHIBITED, EXCCAUSE_STORE_PROHIBITED};
     // initialize buffered save log to flash
     memset(stack_trace_buffer, 0, STACK_TRACE_BUFFER_N);
     memset(stack_trace_context.buffer, 0, STACK_TRACE_BUFFER_N);
     stack_trace_context.flash_index = 0;
     stack_trace_context.buffer_index = 0;
     for (i = 0; i < (sizeof(exno) / sizeof(exno[0])); i++) {
         _xtos_set_exception_handler(exno[i], exception_handler);
     }
 }
getaregval()
static ICACHE_FLASH_ATTR unsigned int getaregval (int reg) static
Definition at line 30 of file exception_handler.c.
References XTensa_exception_frame_s::a, XTensa_exception_frame_s::a0, XTensa_exception_frame_s::a1, ICACHE_FLASH_ATTR, and saved_regs.
Referenced by print_reason().
{
     if (reg == 0) return saved_regs.a0;
     if (reg == 1) return saved_regs.a1;
     return saved_regs.a[reg-2];
 }
print_reason()
static ICACHE_FLASH_ATTR void print_reason () static
Definition at line 81 of file exception_handler.c.
References XTensa_exception_frame_s::a1, XTensa_exception_frame_s::excvaddr, getaregval(), ICACHE_FLASH_ATTR, XTensa_exception_frame_s::pc, print_stack(), printf, XTensa_exception_frame_s::ps, XTensa_exception_frame_s::reason, XTensa_exception_frame_s::sar, saved_regs, stack_trace_append(), stack_trace_buffer, STACK_TRACE_BUFFER_N, tfp_snprintf(), and XTensa_exception_frame_s::vpri.
Referenced by exception_handler().
{
     unsigned int i;
     unsigned int r;
     //register uint32_t sp asm("a1");
     struct XTensa_exception_frame_s *reg = &saved_regs;
 #ifdef DEBUG
     printf("\n\n***** Fatal exception %ld\n", (long int) reg->reason);
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "\n\n***** Fatal exception %ld\n", (long int) reg->reason);
     stack_trace_append(stack_trace_buffer);
 #ifdef DEBUG
     printf("pc=0x%08lx sp=0x%08lx excvaddr=0x%08lx\n",
         (long unsigned int) reg->pc,
         (long unsigned int) reg->a1,
         (long unsigned int) reg->excvaddr);
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "pc=0x%08lx sp=0x%08lx excvaddr=0x%08lx\n",
         (long unsigned int) reg->pc,
         (long unsigned int) reg->a1,
         (long unsigned int) reg->excvaddr);
     stack_trace_append(stack_trace_buffer);
 #ifdef DEBUG
     printf("ps=0x%08lx sar=0x%08lx vpri=0x%08lx\n",
         (long unsigned int) reg->ps,
         (long unsigned int) reg->sar,
         (long unsigned int) reg->vpri);
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "ps=0x%08lx sar=0x%08lx vpri=0x%08lx\n",
         (long unsigned int) reg->ps,
         (long unsigned int) reg->sar,
         (long unsigned int) reg->vpri);
     stack_trace_append(stack_trace_buffer);
     for (i = 0; i < 16; i++) {
         r = getaregval(i);
 #ifdef DEBUG
         printf("r%02u: 0x%08x=%10u ", i, r, r);
 #endif  // DEBUG
         tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "r%02d: 0x%08x=%10d ", i, r, r);
         stack_trace_append(stack_trace_buffer);
         if (i%3 == 2) {
 #ifdef DEBUG
             printf("\n");
 #endif  // DEBUG
             tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "\n");
             stack_trace_append(stack_trace_buffer);
         }
     }
 #ifdef DEBUG
     printf("\n");
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "\n");
     stack_trace_append(stack_trace_buffer);
     //print_stack(reg->pc, sp, 0x3fffffb0);
     print_stack(getaregval(1), 0x3fffffb0);
 }
print_stack()
static ICACHE_FLASH_ATTR void print_stack (uint32_t start, uint32_t end) static
Definition at line 37 of file exception_handler.c.
References ICACHE_FLASH_ATTR, printf, stack_trace_append(), stack_trace_buffer, STACK_TRACE_BUFFER_N, stack_trace_last(), and tfp_snprintf().
Referenced by print_reason().
{
     uint32_t pos;
     uint32_t *values;
     bool looks_like_stack_frame;
 #ifdef DEBUG
     printf("\nStack dump:\n");
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "\nStack dump:\n");
     stack_trace_append(stack_trace_buffer);
     for (pos = start; pos < end; pos += 0x10) {
         values = (uint32_t*)(pos);
         // rough indicator: stack frames usually have SP saved as the second word
         looks_like_stack_frame = (values[2] == pos + 0x10);
 #ifdef DEBUG
         printf("%08lx:  %08lx %08lx %08lx %08lx %c\n",
             (long unsigned int) pos,
             (long unsigned int) values[0],
             (long unsigned int) values[1],
             (long unsigned int) values[2],
             (long unsigned int) values[3],
             (looks_like_stack_frame)?'<':' ');
 #endif  // DEBUG
         tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "%08lx:  %08lx %08lx %08lx %08lx %c\n",
             (long unsigned int) pos,
             (long unsigned int) values[0],
             (long unsigned int) values[1],
             (long unsigned int) values[2],
             (long unsigned int) values[3],
             (looks_like_stack_frame)?'<':' ');
             stack_trace_append(stack_trace_buffer);
     }
 #ifdef DEBUG
     printf("\n");
 #endif  // DEBUG
     tfp_snprintf(stack_trace_buffer, STACK_TRACE_BUFFER_N, "\n");
     stack_trace_append(stack_trace_buffer);
     stack_trace_last();
 }
save_extra_sfrs_for_exception()
void save_extra_sfrs_for_exception ()
Referenced by exception_handler().
stack_trace_append()
ICACHE_FLASH_ATTR void stack_trace_append (char * c)
Definition at line 187 of file exception_handler.c.
References stack_trace_context_t::buffer, stack_trace_context_t::buffer_index, stack_trace_context_t::flash_index, ICACHE_FLASH_ATTR, memcpy, memset, SPI_FLASH_SEC_SIZE, spi_flash_write(), STACK_TRACE_BUFFER_N, stack_trace_context, STACK_TRACE_N, STACK_TRACE_SEC, and strlen.
Referenced by print_reason(), and print_stack().
{
     unsigned int len;
     len = strlen(c);
     if (len == 0) return;
     // only save up to STACK_TRACE_N bytes
     if ((stack_trace_context.flash_index * STACK_TRACE_BUFFER_N) > STACK_TRACE_N) return;
     if (len + stack_trace_context.buffer_index < STACK_TRACE_BUFFER_N) {
         // fill into buffer
         memcpy(stack_trace_context.buffer + stack_trace_context.buffer_index, c, len);
         stack_trace_context.buffer_index += len;
     }
     else {
         // data longer than buffer size, we need to split writes
         // data enough left to fill buffer
         memcpy(stack_trace_context.buffer + stack_trace_context.buffer_index, c, STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index);
         spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                         (uint32_t *)stack_trace_context.buffer,
                         STACK_TRACE_BUFFER_N);
         c += STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index;
         len = strlen(c);
         stack_trace_context.flash_index++;
         stack_trace_context.buffer_index = 0;
         // while enough data fill whole buffer
         while (len > STACK_TRACE_BUFFER_N) {
             c += STACK_TRACE_BUFFER_N * stack_trace_context.flash_index + (STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index);
             memcpy(stack_trace_context.buffer, c, STACK_TRACE_BUFFER_N);
             spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                             (uint32_t *)stack_trace_context.buffer,
                             STACK_TRACE_BUFFER_N);
             len -= STACK_TRACE_BUFFER_N;
             stack_trace_context.flash_index++;
         }
         // last data
         if (len) {
             memset(stack_trace_context.buffer, 0, STACK_TRACE_BUFFER_N);
             memcpy(stack_trace_context.buffer, c, strlen(c));
             stack_trace_context.buffer_index = len;
         }
     }
 }
stack_trace_last()
ICACHE_FLASH_ATTR void stack_trace_last ()
Definition at line 234 of file exception_handler.c.
References stack_trace_context_t::buffer, stack_trace_context_t::flash_index, SPI_FLASH_SEC_SIZE, spi_flash_write(), STACK_TRACE_BUFFER_N, stack_trace_context, and STACK_TRACE_SEC.
Referenced by print_stack().
{
     spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                     (uint32_t *)stack_trace_context.buffer,
                     STACK_TRACE_BUFFER_N);
 }
Variable Documentation
saved_regs
struct XTensa_exception_frame_s saved_regs
Definition at line 11 of file exception_handler.c.
Referenced by exception_handler(), getaregval(), and print_reason().
stack_trace_buffer
char stack_trace_buffer[STACK_TRACE_BUFFER_N]
Definition at line 20 of file exception_handler.c.
Referenced by exception_handler_init(), print_reason(), and print_stack().
stack_trace_context
struct stack_trace_context_t stack_trace_context
Referenced by exception_handler_init(), stack_trace_append(), and stack_trace_last().