MeterLogger: user/exception_handler.h File Reference
exception_handler.h File Reference
#include <esp8266.h>
#include "xtensa/corebits.h"
Data Structures
struct XTensa_exception_frame_s
Functions
ICACHE_FLASH_ATTR void exception_handler_init ()
ICACHE_FLASH_ATTR void stack_trace_append (char *c)
ICACHE_FLASH_ATTR void stack_trace_last ()
Function Documentation
exception_handler_init()
ICACHE_FLASH_ATTR void exception_handler_init ()
Definition at line 169 of file exception_handler.c.
References _xtos_set_exception_handler(), stack_trace_context_t::buffer, stack_trace_context_t::buffer_index, exception_handler(), stack_trace_context_t::flash_index, ICACHE_FLASH_ATTR, memset, stack_trace_buffer, STACK_TRACE_BUFFER_N, and stack_trace_context.
Referenced by mqtt_rpc_restart().
{
     unsigned int i;
     int exno[] = {EXCCAUSE_ILLEGAL, EXCCAUSE_INSTR_ERROR, EXCCAUSE_DIVIDE_BY_ZERO, EXCCAUSE_UNALIGNED,
                   EXCCAUSE_INSTR_DATA_ERROR, EXCCAUSE_LOAD_STORE_DATA_ERROR, EXCCAUSE_INSTR_ADDR_ERROR,
                   EXCCAUSE_LOAD_STORE_ADDR_ERROR, EXCCAUSE_INSTR_PROHIBITED, EXCCAUSE_LOAD_PROHIBITED, EXCCAUSE_STORE_PROHIBITED};
     // initialize buffered save log to flash
     memset(stack_trace_buffer, 0, STACK_TRACE_BUFFER_N);
     memset(stack_trace_context.buffer, 0, STACK_TRACE_BUFFER_N);
     stack_trace_context.flash_index = 0;
     stack_trace_context.buffer_index = 0;
     for (i = 0; i < (sizeof(exno) / sizeof(exno[0])); i++) {
         _xtos_set_exception_handler(exno[i], exception_handler);
     }
 }
stack_trace_append()
ICACHE_FLASH_ATTR void stack_trace_append (char * c)
Definition at line 187 of file exception_handler.c.
References stack_trace_context_t::buffer, stack_trace_context_t::buffer_index, stack_trace_context_t::flash_index, ICACHE_FLASH_ATTR, memcpy, memset, SPI_FLASH_SEC_SIZE, spi_flash_write(), STACK_TRACE_BUFFER_N, stack_trace_context, STACK_TRACE_N, STACK_TRACE_SEC, and strlen.
Referenced by print_reason(), and print_stack().
{
     unsigned int len;
     len = strlen(c);
     if (len == 0) return;
     // only save up to STACK_TRACE_N bytes
     if ((stack_trace_context.flash_index * STACK_TRACE_BUFFER_N) > STACK_TRACE_N) return;
     if (len + stack_trace_context.buffer_index < STACK_TRACE_BUFFER_N) {
         // fill into buffer
         memcpy(stack_trace_context.buffer + stack_trace_context.buffer_index, c, len);
         stack_trace_context.buffer_index += len;
     }
     else {
         // data longer than buffer size, we need to split writes
         // data enough left to fill buffer
         memcpy(stack_trace_context.buffer + stack_trace_context.buffer_index, c, STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index);
         spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                         (uint32_t *)stack_trace_context.buffer,
                         STACK_TRACE_BUFFER_N);
         c += STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index;
         len = strlen(c);
         stack_trace_context.flash_index++;
         stack_trace_context.buffer_index = 0;
         // while enough data fill whole buffer
         while (len > STACK_TRACE_BUFFER_N) {
             c += STACK_TRACE_BUFFER_N * stack_trace_context.flash_index + (STACK_TRACE_BUFFER_N - stack_trace_context.buffer_index);
             memcpy(stack_trace_context.buffer, c, STACK_TRACE_BUFFER_N);
             spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                             (uint32_t *)stack_trace_context.buffer,
                             STACK_TRACE_BUFFER_N);
             len -= STACK_TRACE_BUFFER_N;
             stack_trace_context.flash_index++;
         }
         // last data
         if (len) {
             memset(stack_trace_context.buffer, 0, STACK_TRACE_BUFFER_N);
             memcpy(stack_trace_context.buffer, c, strlen(c));
             stack_trace_context.buffer_index = len;
         }
     }
 }
stack_trace_last()
ICACHE_FLASH_ATTR void stack_trace_last ()
Definition at line 234 of file exception_handler.c.
References stack_trace_context_t::buffer, stack_trace_context_t::flash_index, SPI_FLASH_SEC_SIZE, spi_flash_write(), STACK_TRACE_BUFFER_N, stack_trace_context, and STACK_TRACE_SEC.
Referenced by print_stack().
{
     spi_flash_write((STACK_TRACE_SEC * SPI_FLASH_SEC_SIZE) + (stack_trace_context.flash_index * STACK_TRACE_BUFFER_N),
                     (uint32_t *)stack_trace_context.buffer,
                     STACK_TRACE_BUFFER_N);
 }