MeterLogger: user/httpd.h File Reference
httpd.h File Reference
#include <c_types.h>
#include <esp8266.h>
Data Structures
struct HttpdConnData
struct HttpdBuiltInUrl
Macros
#define HTTPDVER "0.2"
#define HTTPD_CGI_MORE 0
#define HTTPD_CGI_DONE 1
#define HTTPD_CGI_NOTFOUND 2
#define HTTPD_CGI_AUTHENTICATED 2
#define HTTPD_CGI_SERVER_ERROR 3
Typedefs
typedef struct HttpdPriv HttpdPriv
typedef struct HttpdConnData HttpdConnData
typedef int(* cgiSendCallback) (HttpdConnData *connData)
Functions
ICACHE_FLASH_ATTR int cgiRedirect (HttpdConnData *connData)
ICACHE_FLASH_ATTR void httpdRedirect (HttpdConnData *conn, char *newUrl)
int httpdUrlDecode (char *val, int valLen, char *ret, int retLen)
ICACHE_FLASH_ATTR int httpdFindArg (char *line, char *arg, char *buff, int buffLen)
ICACHE_FLASH_ATTR void httpdInit (HttpdBuiltInUrl *fixedUrls, int port)
const char * httpdGetMimetype (char *url)
ICACHE_FLASH_ATTR void httpdStartResponse (HttpdConnData *conn, int code)
ICACHE_FLASH_ATTR void httpdHeader (HttpdConnData *conn, const char *field, const char *val)
ICACHE_FLASH_ATTR void httpdEndHeaders (HttpdConnData *conn)
ICACHE_FLASH_ATTR int httpdGetHeader (HttpdConnData *conn, char *header, char *ret, int retLen)
ICACHE_FLASH_ATTR int httpdSend (HttpdConnData *conn, const char *data, int len)
ICACHE_FLASH_ATTR void httpdStop ()
Macro Definition Documentation
HTTPD_CGI_AUTHENTICATED
#define HTTPD_CGI_AUTHENTICATED 2
Definition at line 11 of file httpd.h.
Referenced by authBasic().
HTTPD_CGI_DONE
#define HTTPD_CGI_DONE 1
Definition at line 9 of file httpd.h.
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), cgiRedirect(), cgiSetup(), cgiWiFiScan(), cgiWifiSetMode(), httpdSendResp(), and httpdSentCb().
HTTPD_CGI_MORE
#define HTTPD_CGI_MORE 0
Definition at line 8 of file httpd.h.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
HTTPD_CGI_NOTFOUND
#define HTTPD_CGI_NOTFOUND 2
Definition at line 10 of file httpd.h.
Referenced by cgiEspFsHook(), cgiEspFsTemplate(), and httpdSendResp().
HTTPD_CGI_SERVER_ERROR
#define HTTPD_CGI_SERVER_ERROR 3
Definition at line 12 of file httpd.h.
Referenced by cgiWiFiScan(), and httpdSendResp().
HTTPDVER
#define HTTPDVER "0.2"
Definition at line 6 of file httpd.h.
Referenced by httpdStartResponse().
Typedef Documentation
cgiSendCallback
typedef int(* cgiSendCallback) (HttpdConnData *connData)
Definition at line 17 of file httpd.h.
HttpdConnData
typedef struct HttpdConnData HttpdConnData
Definition at line 15 of file httpd.h.
HttpdPriv
typedef struct HttpdPriv HttpdPriv
Definition at line 14 of file httpd.h.
Function Documentation
cgiRedirect()
ICACHE_FLASH_ATTR int cgiRedirect (HttpdConnData * connData)
Definition at line 253 of file httpd.c.
References HttpdConnData::cgiArg, HttpdConnData::conn, HTTPD_CGI_DONE, httpdRedirect(), ICACHE_FLASH_ATTR, and NULL.
{
     if (connData->conn==NULL) {
         //Connection aborted. Clean up.
         return HTTPD_CGI_DONE;
     }
     httpdRedirect(connData, (char*)connData->cgiArg);
     return HTTPD_CGI_DONE;
 }
httpdEndHeaders()
ICACHE_FLASH_ATTR void httpdEndHeaders (HttpdConnData * conn)
Definition at line 237 of file httpd.c.
References httpdSend(), and ICACHE_FLASH_ATTR.
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     httpdSend(conn, "\r\n", -1);
 }
httpdFindArg()
ICACHE_FLASH_ATTR int httpdFindArg (char * line, char * arg, char * buff, int buffLen)
Definition at line 164 of file httpd.c.
References httpdUrlDecode(), ICACHE_FLASH_ATTR, INFO, NULL, os_strlen, os_strncmp, os_strstr, and strlen.
Referenced by cgiSetup(), and cgiWifiSetMode().
{
     char *p, *e;
     if (line==NULL) return 0;
     p=line;
     while(p!=NULL && *p!='\n' && *p!='\r' && *p!=0) {
         INFO("findArg: %s\n", p);
         if (os_strncmp(p, arg, os_strlen(arg))==0 && p[strlen(arg)]=='=') {
             p+=os_strlen(arg)+1; //move p to start of value
             e=(char*)os_strstr(p, "&");
             if (e==NULL) e=p+os_strlen(p);
             INFO("findArg: val %s len %d\n", p, (e-p));
             return httpdUrlDecode(p, (e-p), buff, buffLen);
         }
         p=(char*)os_strstr(p, "&");
         if (p!=NULL) p+=1;
     }
     INFO("Finding %s in %s: Not found :/\n", arg, line);
     return -1; //not found
 }
httpdGetHeader()
ICACHE_FLASH_ATTR int httpdGetHeader (HttpdConnData * conn, char * header, char * ret, int retLen)
Definition at line 186 of file httpd.c.
References HttpdPriv::head, HttpdPriv::headPos, ICACHE_FLASH_ATTR, os_strncmp, HttpdConnData::priv, and strlen.
Referenced by authBasic().
{
     char *p=conn->priv->head;
     p=p+strlen(p)+1; //skip GET/POST part
     p=p+strlen(p)+1; //skip HTTP part
     while (p<(conn->priv->head+conn->priv->headPos)) {
         while(*p<=32 && *p!=0) p++; //skip crap at start
 //      INFO("Looking for %s, Header: '%s'\n", header, p);
         //See if this is the header
         if (os_strncmp(p, header, strlen(header))==0 && p[strlen(header)]==':') {
             //Skip 'key:' bit of header line
             p=p+strlen(header)+1;
             //Skip past spaces after the colon
             while(*p==' ') p++;
             //Copy from p to end
             while (*p!=0 && *p!='\r' && *p!='\n' && retLen>1) {
                 *ret++=*p++;
                 retLen--;
             }
             //Zero-terminate string
             *ret=0;
             //All done :)
             return 1;
         }
         p+=strlen(p)+1; //Skip past end of string and \0 terminator
     }
     return 0;
 }
httpdGetMimetype()
const char* httpdGetMimetype (char * url)
Definition at line 90 of file httpd.c.
References ICACHE_FLASH_ATTR, MimeMap::mimetype, NULL, os_strcmp, and strlen.
Referenced by cgiEspFsHook(), and cgiEspFsTemplate().
{
     int i=0;
     //Go find the extension
     char *ext=url+(strlen(url)-1);
     while (ext!=url && *ext!='.') ext--;
     if (*ext=='.') ext++;
     //ToDo: os_strcmp is case sensitive; we may want to do case-intensive matching here...
     while (mimeTypes[i].ext!=NULL && os_strcmp(ext, mimeTypes[i].ext)!=0) i++;
     return mimeTypes[i].mimetype;
 }
httpdHeader()
ICACHE_FLASH_ATTR void httpdHeader (HttpdConnData * conn, const char * field, const char * val)
Definition at line 226 of file httpd.c.
References httpdSend(), ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     char buff[256];
     int l;
     tfp_snprintf(buff, 256, "%s: %s\r\n", field, val);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdInit()
ICACHE_FLASH_ATTR void httpdInit (HttpdBuiltInUrl * fixedUrls, int port)
Definition at line 516 of file httpd.c.
References cgiWifiInit(), HttpdConnData::conn, espconn_accept(), ESPCONN_NONE, espconn_regist_connectcb(), ESPCONN_TCP, httpdConnectCb(), httpdTcp, ICACHE_FLASH_ATTR, INFO, _esp_tcp::local_port, malloc, MAX_CONN, NULL, espconn::proto, espconn::state, espconn::tcp, and espconn::type.
Referenced by httpd_user_init().
{
     int i;
     connPrivData = malloc(sizeof(HttpdPriv) * MAX_CONN);
     for (i=0; i<MAX_CONN; i++) {
         connData[i].conn=NULL;
     }
     httpdConn.type=ESPCONN_TCP;
     httpdConn.state=ESPCONN_NONE;
     httpdTcp.local_port=port;
     httpdConn.proto.tcp=&httpdTcp;
     builtInUrls=fixedUrls;
     cgiWifiInit();
     INFO("Httpd init, conn=%p\n", &httpdConn);
     espconn_regist_connectcb(&httpdConn, httpdConnectCb);
     espconn_accept(&httpdConn);
 }
httpdRedirect()
ICACHE_FLASH_ATTR void httpdRedirect (HttpdConnData * conn, char * newUrl)
Definition at line 243 of file httpd.c.
References httpdSend(), ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by cgiRedirect(), cgiSetup(), and cgiWifiSetMode().
{
     char buff[1024];
     int l;
     tfp_snprintf(buff, 1024, "HTTP/1.1 302 Found\r\nLocation: %s\r\n\r\nMoved to %s\r\n", newUrl, newUrl);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdSend()
ICACHE_FLASH_ATTR int httpdSend (HttpdConnData * conn, const char * data, int len)
Definition at line 267 of file httpd.c.
References ICACHE_FLASH_ATTR, MAX_SENDBUFF_LEN, os_memcpy, HttpdConnData::priv, HttpdPriv::sendBuff, HttpdPriv::sendBuffLen, and strlen.
Referenced by authBasic(), cgiEspFsTemplate(), cgiWiFiScan(), httpdEndHeaders(), httpdHeader(), httpdRedirect(), httpdSendResp(), httpdStartResponse(), and tplSetup().
{
     if (len<0) len=strlen(data);
     if (conn->priv->sendBuffLen+len>MAX_SENDBUFF_LEN) return 0;
     os_memcpy(conn->priv->sendBuff+conn->priv->sendBuffLen, data, len);
     conn->priv->sendBuffLen+=len;
     return 1;
 }
httpdStartResponse()
ICACHE_FLASH_ATTR void httpdStartResponse (HttpdConnData * conn, int code)
Definition at line 216 of file httpd.c.
References httpdSend(), HTTPDVER, ICACHE_FLASH_ATTR, strlen, and tfp_snprintf().
Referenced by authBasic(), cgiEspFsHook(), cgiEspFsTemplate(), and cgiWiFiScan().
{
     char buff[128];
     int l;
     tfp_snprintf(buff, 128, "HTTP/1.0 %d OK\r\nServer: esp8266-httpd/"HTTPDVER"\r\n", code);
     l = strlen(buff);
     httpdSend(conn, buff, l);
 }
httpdStop()
ICACHE_FLASH_ATTR void httpdStop ()
Definition at line 543 of file httpd.c.
References espconn_delete(), espconn_disconnect(), ESPCONN_NONE, free, httpdDisconnectTimer, httpdDisconnectTimerFunc(), httpdRetireConn(), INFO, NULL, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, and espconn::state.
Referenced by httpdDisconnectTimerFunc(), and system_restart_defered().
                  {
     if (connPrivData == NULL) {
         // allready stopped
         return;
     }
     INFO("Httpd stopping, state=%d conn=%p\n", httpdConn.state, &httpdConn);
     if (httpdConn.state != ESPCONN_NONE) {
         if (espconn_delete(&httpdConn) == 0) {
             os_timer_disarm(&httpdDisconnectTimer);
             httpdRetireConn(connData);
             free(connPrivData);
             connPrivData = NULL;
             INFO("Httpd stopped\n");
         }
         else {
             espconn_disconnect(&httpdConn);
             os_timer_disarm(&httpdDisconnectTimer);
             os_timer_setfn(&httpdDisconnectTimer, (os_timer_func_t *)httpdDisconnectTimerFunc, NULL);
             os_timer_arm(&httpdDisconnectTimer, 1000, 0);
             INFO("Httpd still running rescheduling httpdStop\n");
         }
     }
 }
httpdUrlDecode()
int httpdUrlDecode (char * val, int valLen, char * ret, int retLen)
Definition at line 134 of file httpd.c.
References httpdHexVal(), and ICACHE_FLASH_ATTR.
Referenced by httpdFindArg().
{
     int s=0, d=0;
     int esced=0, escVal=0;
     while (s<valLen && d<retLen) {
         if (esced==1)  {
             escVal=httpdHexVal(val[s])<<4;
             esced=2;
         } else if (esced==2) {
             escVal+=httpdHexVal(val[s]);
             ret[d++]=escVal;
             esced=0;
         } else if (val[s]=='%') {
             esced=1;
         } else if (val[s]=='+') {
             ret[d++]=' ';
         } else {
             ret[d++]=val[s];
         }
         s++;
     }
     if (d<retLen) ret[d]=0;
     return d;
 }