MeterLogger: esp-open-lwip/lwip/netif/tunif.c File Reference
tunif.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/time.h>
#include <lwip/netif.h>
#include <lwip/pbuf.h>
#include <lwip/stats.h>
#include <lwip/ip.h>
#include <lwip/init.h>
#include <lwip/tcp_impl.h>
#include <lwip/dns.h>
#include <netif/tunif.h>
Data Structures
struct tunif_data
Functions
static err_t tunif_output (struct netif *netif, struct pbuf *p, ip_addr_t *ipaddr)
static void tunif_ready (int fd, short events, void *ctx)
static err_t tunif_init (struct netif *netif)
struct tunif_data * tunif_add (struct event_base *base, int fd, int header)
void tunif_del (struct tunif_data *data)
void tunif_set_ipaddr (struct tunif_data *data, uint32_t addr)
void tunif_set_netmask (struct tunif_data *data, uint32_t addr)
void tunif_set_gw (struct tunif_data *data, uint32_t addr)
void tunif_set_up (struct tunif_data *data)
void tunif_set_down (struct tunif_data *data)
void tunif_set_mtu (struct tunif_data *data, int mtu)
void tunif_set_flag (struct tunif_data *data, int flag)
void tunif_clear_flag (struct tunif_data *data, int flag)
void tunif_clear_dns (void)
void tunif_add_dns (uint32_t addr)
Variables
static int dns_count
Function Documentation
tunif_add()
struct tunif_data* tunif_add (struct event_base * base, int fd, int header)
Definition at line 97 of file tunif.c.
References tunif_data::ev, tunif_data::fd, ip_input(), tunif_data::netif, netif_add(), netif_set_default(), NULL, and tunif_init().
 {
     struct tunif_data *data;
 #if 0
     const char *pcap = getenv("TUNIF_PCAP_FILE");
     if (pcap && !pcap_dumper) {
         pcap_t *p;
         p = pcap_open_dead(DLT_RAW, 2000);
         pcap_dumper = pcap_dump_open(p, pcap);
     }
 #endif
     data = calloc(1, sizeof(*data));
     data->fd = fd;
 //  data->header = header;
 //  data->ev = event_new(base, fd, EV_READ | EV_PERSIST, tunif_ready, data);
     event_add(data->ev, NULL);
     netif_add(&data->netif, NULL, NULL, NULL, data, tunif_init, ip_input);
     netif_set_default(&data->netif);
     return data;
 }
tunif_add_dns()
void tunif_add_dns (uint32_t addr)
Definition at line 197 of file tunif.c.
References dns_count.
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     dns_setserver(dns_count++, &ipaddr);
 }
tunif_clear_dns()
void tunif_clear_dns (void)
Definition at line 186 of file tunif.c.
References dns_count, and DNS_MAX_SERVERS.
 {
     ip_addr_t addr;
 //  addr.addr = INADDR_ANY;
     int i;
     for (i = 0; i < DNS_MAX_SERVERS; i++)
         dns_setserver(i, &addr);
     dns_count = 0;
 }
tunif_clear_flag()
void tunif_clear_flag (struct tunif_data * data, int flag)
Definition at line 178 of file tunif.c.
References netif::flags, and tunif_data::netif.
 {
     data->netif.flags &= ~flag;
 }
tunif_del()
void tunif_del (struct tunif_data * data)
Definition at line 121 of file tunif.c.
References tunif_data::ev, free, tunif_data::netif, and netif_remove().
 {
     netif_remove(&data->netif);
     event_del(data->ev);
     event_free(data->ev);
     free(data);
 }
tunif_init()
static err_t tunif_init (struct netif * netif) static
Definition at line 83 of file tunif.c.
References netif::flags, netif::mtu, netif::name, NETIF_FLAG_LINK_UP, NETIF_INIT_SNMP, netif::output, snmp_ifType_other, and tunif_output().
Referenced by tunif_add().
 {
     NETIF_INIT_SNMP(netif, snmp_ifType_other, 0);
     netif->name[0] = 't';
     netif->name[1] = 'p';
     netif->output = tunif_output;
     netif->mtu = 1360;
     netif->flags = NETIF_FLAG_LINK_UP;
     return 0;
 }
tunif_output()
static err_t tunif_output (struct netif * netif, struct pbuf * p, ip_addr_t * ipaddr) static
Definition at line 26 of file tunif.c.
References tunif_data::buf, tunif_data::fd, LINK_STATS_INC, NULL, pbuf_copy_partial(), and netif::state.
Referenced by tunif_init().
 {
     struct tunif_data *data = netif->state;
     int len;
     len = pbuf_copy_partial(p, data->buf, sizeof(data->buf), 0);
 #if 0
     if (pcap_dumper) {
         struct pcap_pkthdr hdr = {.caplen = len, .len = len};
         gettimeofday(&hdr.ts, NULL);
         pcap_dump((void *) pcap_dumper, &hdr, data->buf);
     }
 #endif
     len = write(data->fd, data->buf, len);
 #if 0
     if (len < 0)
         LINK_STATS_INC(link.drop);
     else
         LINK_STATS_INC(link.xmit);
 #endif
     return 0;
 }
tunif_ready()
static void tunif_ready (int fd, short events, void * ctx) static
Definition at line 51 of file tunif.c.
References tunif_data::buf, tunif_data::ev, netif::input, LINK_STATS_INC, tunif_data::netif, NULL, pbuf_alloc(), pbuf_free(), PBUF_IP, PBUF_POOL, and pbuf_take().
 {
     struct tunif_data *data = ctx;
     int ret;
 //  ret = read(fd, data->buf, sizeof(data->buf));
     if ((ret < 0 && errno != EAGAIN) || !ret) {
         /* FATAL */
         event_del(data->ev);
     } else if (ret > 0) {
         struct pbuf *p;
         p = pbuf_alloc(PBUF_IP, ret, PBUF_POOL);
 #if 0
         if (!p) {
             LINK_STATS_INC(link.memerr);
             LINK_STATS_INC(link.drop);
             return;
         }
         LINK_STATS_INC(link.recv);
         if (pcap_dumper) {
             struct pcap_pkthdr hdr = {.caplen = ret, .len = ret};
             gettimeofday(&hdr.ts, NULL);
             pcap_dump((void *) pcap_dumper, &hdr, data->buf);
         }
 #endif
         pbuf_take(p, data->buf, ret);
         if (data->netif.input(p, &data->netif) < 0)
             pbuf_free(p);
     }
 }
tunif_set_down()
void tunif_set_down (struct tunif_data * data)
Definition at line 160 of file tunif.c.
References tunif_data::netif, and netif_set_down().
 {
     netif_set_down(&data->netif);
 }
tunif_set_flag()
void tunif_set_flag (struct tunif_data * data, int flag)
Definition at line 172 of file tunif.c.
References netif::flags, and tunif_data::netif.
 {
     data->netif.flags |= flag;
 }
tunif_set_gw()
void tunif_set_gw (struct tunif_data * data, uint32_t addr)
Definition at line 146 of file tunif.c.
References tunif_data::netif, and netif_set_gw().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_gw(&data->netif, &ipaddr);
 }
tunif_set_ipaddr()
void tunif_set_ipaddr (struct tunif_data * data, uint32_t addr)
Definition at line 130 of file tunif.c.
References tunif_data::netif, and netif_set_ipaddr().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_ipaddr(&data->netif, &ipaddr);
 }
tunif_set_mtu()
void tunif_set_mtu (struct tunif_data * data, int mtu)
Definition at line 166 of file tunif.c.
References netif::mtu, and tunif_data::netif.
 {
     data->netif.mtu = mtu;
 }
tunif_set_netmask()
void tunif_set_netmask (struct tunif_data * data, uint32_t addr)
Definition at line 138 of file tunif.c.
References tunif_data::netif, and netif_set_netmask().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_netmask(&data->netif, &ipaddr);
 }
tunif_set_up()
void tunif_set_up (struct tunif_data * data)
Definition at line 154 of file tunif.c.
References tunif_data::netif, and netif_set_up().
 {
     netif_set_up(&data->netif);
 }
Variable Documentation
dns_count
int dns_count static
Definition at line 183 of file tunif.c.
Referenced by tunif_add_dns(), and tunif_clear_dns().