MeterLogger: esp-open-lwip/include/netif/tunif.h File Reference
tunif.h File Reference
#include "c_types.h"
#include "lwip/opt.h"
#include "lwip/netif.h"
Macros
#define NETIF_FLAG_BROADCAST 0x02U
#define NETIF_FLAG_POINTTOPOINT 0x04U
Functions
struct tunif_data * tunif_add (struct event_base *base, int fd, int header)
void tunif_del (struct tunif_data *data)
void tunif_set_ipaddr (struct tunif_data *data, uint32_t addr)
void tunif_set_netmask (struct tunif_data *data, uint32_t addr)
void tunif_set_gw (struct tunif_data *data, uint32_t addr)
void tunif_set_up (struct tunif_data *data)
void tunif_set_down (struct tunif_data *data)
void tunif_set_mtu (struct tunif_data *data, int mtu)
void tunif_set_flag (struct tunif_data *data, int flag)
void tunif_clear_flag (struct tunif_data *data, int flag)
void tunif_clear_dns (void)
void tunif_add_dns (uint32_t addr)
Macro Definition Documentation
NETIF_FLAG_BROADCAST
#define NETIF_FLAG_BROADCAST 0x02U
Definition at line 8 of file tunif.h.
NETIF_FLAG_POINTTOPOINT
#define NETIF_FLAG_POINTTOPOINT 0x04U
Definition at line 9 of file tunif.h.
Function Documentation
tunif_add()
struct tunif_data* tunif_add (struct event_base * base, int fd, int header)
Definition at line 97 of file tunif.c.
References tunif_data::ev, tunif_data::fd, ip_input(), tunif_data::netif, netif_add(), netif_set_default(), NULL, and tunif_init().
 {
     struct tunif_data *data;
 #if 0
     const char *pcap = getenv("TUNIF_PCAP_FILE");
     if (pcap && !pcap_dumper) {
         pcap_t *p;
         p = pcap_open_dead(DLT_RAW, 2000);
         pcap_dumper = pcap_dump_open(p, pcap);
     }
 #endif
     data = calloc(1, sizeof(*data));
     data->fd = fd;
 //  data->header = header;
 //  data->ev = event_new(base, fd, EV_READ | EV_PERSIST, tunif_ready, data);
     event_add(data->ev, NULL);
     netif_add(&data->netif, NULL, NULL, NULL, data, tunif_init, ip_input);
     netif_set_default(&data->netif);
     return data;
 }
tunif_add_dns()
void tunif_add_dns (uint32_t addr)
Definition at line 197 of file tunif.c.
References dns_count.
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     dns_setserver(dns_count++, &ipaddr);
 }
tunif_clear_dns()
void tunif_clear_dns (void)
Definition at line 186 of file tunif.c.
References dns_count, and DNS_MAX_SERVERS.
 {
     ip_addr_t addr;
 //  addr.addr = INADDR_ANY;
     int i;
     for (i = 0; i < DNS_MAX_SERVERS; i++)
         dns_setserver(i, &addr);
     dns_count = 0;
 }
tunif_clear_flag()
void tunif_clear_flag (struct tunif_data * data, int flag)
Definition at line 178 of file tunif.c.
References netif::flags, and tunif_data::netif.
 {
     data->netif.flags &= ~flag;
 }
tunif_del()
void tunif_del (struct tunif_data * data)
Definition at line 121 of file tunif.c.
References tunif_data::ev, free, tunif_data::netif, and netif_remove().
 {
     netif_remove(&data->netif);
     event_del(data->ev);
     event_free(data->ev);
     free(data);
 }
tunif_set_down()
void tunif_set_down (struct tunif_data * data)
Definition at line 160 of file tunif.c.
References tunif_data::netif, and netif_set_down().
 {
     netif_set_down(&data->netif);
 }
tunif_set_flag()
void tunif_set_flag (struct tunif_data * data, int flag)
Definition at line 172 of file tunif.c.
References netif::flags, and tunif_data::netif.
 {
     data->netif.flags |= flag;
 }
tunif_set_gw()
void tunif_set_gw (struct tunif_data * data, uint32_t addr)
Definition at line 146 of file tunif.c.
References tunif_data::netif, and netif_set_gw().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_gw(&data->netif, &ipaddr);
 }
tunif_set_ipaddr()
void tunif_set_ipaddr (struct tunif_data * data, uint32_t addr)
Definition at line 130 of file tunif.c.
References tunif_data::netif, and netif_set_ipaddr().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_ipaddr(&data->netif, &ipaddr);
 }
tunif_set_mtu()
void tunif_set_mtu (struct tunif_data * data, int mtu)
Definition at line 166 of file tunif.c.
References netif::mtu, and tunif_data::netif.
 {
     data->netif.mtu = mtu;
 }
tunif_set_netmask()
void tunif_set_netmask (struct tunif_data * data, uint32_t addr)
Definition at line 138 of file tunif.c.
References tunif_data::netif, and netif_set_netmask().
 {
     ip_addr_t ipaddr;
     ipaddr.addr = addr;
     netif_set_netmask(&data->netif, &ipaddr);
 }
tunif_set_up()
void tunif_set_up (struct tunif_data * data)
Definition at line 154 of file tunif.c.
References tunif_data::netif, and netif_set_up().
 {
     netif_set_up(&data->netif);
 }