MeterLogger: user/utils.c File Reference
utils.c File Reference
#include <esp8266.h>
#include <string.h>
#include "config.h"
#include "user_config.h"
#include "debug.h"
#include "wifi.h"
#include "httpd.h"
#include "captdns.h"
#include "unix_time.h"
#include "cron/cron.h"
#include "led.h"
#include "watchdog.h"
#include "tinyprintf.h"
#include "utils.h"
Functions
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t *data_p, unsigned int length)
ICACHE_FLASH_ATTR void multiply_str_by_1000 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void kw_to_w_str (char *kw, char *w)
ICACHE_FLASH_ATTR void mw_to_kw_str (char *mw, char *w)
ICACHE_FLASH_ATTR void divide_str_by_10 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void divide_str_by_100 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void divide_str_by_1000 (char *str, char *decimal_str)
ICACHE_FLASH_ATTR void w_to_kw_str (char *w, char *kw)
ICACHE_FLASH_ATTR void cleanup_decimal_str (char *decimal_str, char *cleaned_up_str, unsigned int length)
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
ICACHE_FLASH_ATTR int int_pow (int x, int y)
ICACHE_FLASH_ATTR int query_string_escape (char *str, size_t size)
ICACHE_FLASH_ATTR int query_string_unescape (char *str)
ICACHE_FLASH_ATTR size_t spi_flash_size ()
ICACHE_FLASH_ATTR static void system_restart_defered_timer_func (void *arg)
ICACHE_FLASH_ATTR void system_restart_defered ()
Variables
static os_timer_t system_restart_defered_timer
const uint16_t ccit_crc16_table [256]
Function Documentation
ccit_crc16()
ICACHE_FLASH_ATTR uint16_t ccit_crc16 (uint16_t crc16, uint8_t * data_p, unsigned int length)
Definition at line 64 of file utils.c.
Referenced by cfg_load(), cfg_save(), and kmp_crc16().
{
     while (length--) {
         crc16 = (crc16 << 8) ^ ccit_crc16_table[((crc16 >> 8) ^ *data_p++) & 0x00FF];
     }
     return crc16;
 }
cleanup_decimal_str()
ICACHE_FLASH_ATTR void cleanup_decimal_str (char * decimal_str, char * cleaned_up_str, unsigned int length)
Definition at line 196 of file utils.c.
References decimal_number_length(), ICACHE_FLASH_ATTR, memcpy, NULL, strcat, strncpy, strstr, and tfp_snprintf().
Referenced by parse_en61107_frame(), and parse_mc66cde_standard_data_1_frame().
{
     uint32_t value_int, value_frac;
     char *pos;
     uint8_t decimals = 0;
     uint8_t prepend_zeroes;
     char zeroes[8];
     memcpy(cleaned_up_str, decimal_str, length);
     cleaned_up_str[length] = 0; // null terminate
     pos = strstr(cleaned_up_str, ".");
     if (pos == NULL) {
         // non fractional number
         value_int = atoi(cleaned_up_str);
         tfp_snprintf(cleaned_up_str, length, "%u", value_int);
     }
     else {
         // parse frac
         while ((*(pos + 1 + decimals) >= '0') && (*(pos + 1 + decimals) <= '9')) {
             // count the decimals
             decimals++;
         }
         value_frac = atoi(pos + 1);
         prepend_zeroes = decimals - decimal_number_length(atoi(pos + 1));
         zeroes[0] = 0;  // null terminate
         while (prepend_zeroes--) {
             strcat(zeroes, "0");
         }
         // parse int
         strncpy(cleaned_up_str, decimal_str, (pos - cleaned_up_str));
         cleaned_up_str[cleaned_up_str - pos] = 0;   // null terminate
         value_int = atoi(cleaned_up_str);
         tfp_snprintf(cleaned_up_str, length, "%u.%s%u", value_int, zeroes, value_frac);
     }
 }
decimal_number_length()
ICACHE_FLASH_ATTR unsigned int decimal_number_length (int n)
Definition at line 236 of file utils.c.
References ICACHE_FLASH_ATTR.
Referenced by cleanup_decimal_str(), and kmp_value_to_string().
{
     int digits;
     digits = n < 0; //count "minus"
     do {
         digits++;
     } while (n /= 10);
     return digits;
 }
divide_str_by_10()
ICACHE_FLASH_ATTR void divide_str_by_10 (char * str, char * decimal_str)
Definition at line 119 of file utils.c.
References tfp_snprintf().
Referenced by parse_mc66cde_standard_data_1_frame().
{
     int32_t result_int, result_frac;
     int32_t value_int;
     bool negative;
     value_int = atoi(str);
     negative = (value_int < 0) ? true : false;
     if (negative) {
         value_int = -value_int;
     }
     // ...divide by 10 and prepare decimal string
     result_int = value_int / 10;
     result_frac = value_int % 10;
     if (negative) {
         tfp_snprintf(decimal_str, 8, "-%u.%01u", result_int, result_frac);
     }
     else {
         tfp_snprintf(decimal_str, 8, "%u.%01u", result_int, result_frac);
     }
 }
divide_str_by_100()
ICACHE_FLASH_ATTR void divide_str_by_100 (char * str, char * decimal_str)
Definition at line 143 of file utils.c.
References tfp_snprintf().
Referenced by parse_mc66cde_inst_values_frame(), and parse_mc66cde_standard_data_1_frame().
{
     int32_t result_int, result_frac;
     int32_t value_int;
     bool negative;
     value_int = atoi(str);
     negative = (value_int < 0) ? true : false;
     if (negative) {
         value_int = -value_int;
     }
     // ...divide by 100 and prepare decimal string
     result_int = value_int / 100;
     result_frac = value_int % 100;
     if (negative) {
         tfp_snprintf(decimal_str, 15, "-%u.%02u", result_int, result_frac);
     }
     else {
         tfp_snprintf(decimal_str, 15, "%u.%02u", result_int, result_frac);
     }
 }
divide_str_by_1000()
ICACHE_FLASH_ATTR void divide_str_by_1000 (char * str, char * decimal_str)
Definition at line 167 of file utils.c.
References tfp_snprintf().
Referenced by mqtt_rpc_open_until(), mqtt_rpc_open_until_delta(), mqtt_rpc_vdd(), tplSetup(), and w_to_kw_str().
{
     int32_t result_int, result_frac;
     int32_t value_int;
     bool negative;
     value_int = atoi(str);
     negative = (value_int < 0) ? true : false;
     if (negative) {
         value_int = -value_int;
     }
     // ...divide by 1000 and prepare decimal string in kWh
     result_int = value_int / 1000;
     result_frac = value_int % 1000;
     if (negative) {
         tfp_snprintf(decimal_str, 15, "-%u.%03u", result_int, result_frac);
     }
     else {
         tfp_snprintf(decimal_str, 15, "%u.%03u", result_int, result_frac);
     }
 }
int_pow()
ICACHE_FLASH_ATTR int int_pow (int x, int y)
Definition at line 248 of file utils.c.
References ICACHE_FLASH_ATTR.
Referenced by kmp_value_to_double(), kmp_value_to_string(), and multiply_str_by_1000().
{
     int i;
     int result;
     if (y == 0) {
         return 1;
     }
     result = x;
     for (i = 1; i < y; i++) {
         result *= x;
     }
     return result;
 }
kw_to_w_str()
ICACHE_FLASH_ATTR void kw_to_w_str (char * kw, char * w)
Definition at line 109 of file utils.c.
References multiply_str_by_1000().
Referenced by cgiSetup().
{
     // just a wrapper
     multiply_str_by_1000(kw, w);
 }
multiply_str_by_1000()
ICACHE_FLASH_ATTR void multiply_str_by_1000 (char * str, char * decimal_str)
Definition at line 71 of file utils.c.
References int_pow(), strlen, and tfp_snprintf().
Referenced by en61107_get_received_serial(), kmp_received_task(), kw_to_w_str(), mqtt_rpc_open_until(), mqtt_rpc_open_until_delta(), and mw_to_kw_str().
{
     uint32_t result_int, result_frac;
     uint32_t i;
     uint32_t len;
     bool dec_separator;
     char result_int_str[32 + 1];
     uint32_t pos_int;
     uint32_t pos_frac;
     len = strlen(str);
     result_frac = 0;
     pos_int = 0;
     pos_frac = 0;
     dec_separator = false;
     for (i = 0; i < len && pos_frac < 3; i++) {
         if (str[i] == '.') {
             dec_separator = 1;
         }
         else if (!dec_separator) {
             result_int_str[pos_int++] = str[i];
         }
         else {
             //result_frac_str[pos_frac++] = str[i];
             result_frac += (str[i] - '0') * int_pow(10, 2 - pos_frac);
             pos_frac++;
         }
     }
     result_int_str[pos_int] = 0;    // null terminate
     result_int = 1000 * atoi(result_int_str);   // multiply by 1000
     result_int += result_frac;
     tfp_snprintf(decimal_str, 11, "%u", result_int);
 }
mw_to_kw_str()
ICACHE_FLASH_ATTR void mw_to_kw_str (char * mw, char * w)
Definition at line 114 of file utils.c.
References multiply_str_by_1000().
Referenced by en61107_get_received_energy_kwh(), and kmp_received_task().
{
     // just a wrapper
     multiply_str_by_1000(mw, w);
 }
query_string_escape()
ICACHE_FLASH_ATTR int query_string_escape (char * str, size_t size)
Definition at line 264 of file utils.c.
References ICACHE_FLASH_ATTR, memcpy, strlen, and strstr.
Referenced by mqtt_rpc_set_ssid_pwd().
{
     char *p;
     int len;
     int len_escaped;
     // replace "&" with "%26";
     len = strlen(str);
     len_escaped = len;
     for (p = str; (p = strstr(p, "&")); ++p) {
         if (len_escaped + 2 <= size - 1) {
             // if escaped string is inside bounds
             memmove(p + 3, p + 1, len - (p - str) + 1);
             memcpy(p, "\%26", 3);
             len_escaped += 2;
         }
         else {
             return -1;
         }
     }
     // and "=" with "%61";
     len = strlen(str);
     len_escaped = len;
     for (p = str; (p = strstr(p, "=")); ++p) {
         if (len_escaped + 2 <= size - 1) {
             // if escaped string is inside bounds
             memmove(p + 3, p + 1, len - (p - str) + 1);
             memcpy(p, "\%61", 3);
             len_escaped += 2;
         }
         else {
             return -1;
         }
     }
     return strlen(str);
 }
query_string_unescape()
ICACHE_FLASH_ATTR int query_string_unescape (char * str)
Definition at line 302 of file utils.c.
References ICACHE_FLASH_ATTR, memcpy, strlen, and strstr.
Referenced by cfg_save_ssid_pwd().
{
     char *p;
     int len;
     // replace "%26" with "&";
     len = strlen(str);
     for (p = str; (p = strstr(p, "\%26")); ++p) {
         memmove(p + 1, p + 3, len - (p - str) + 1);
         memcpy(p, "&", 1);
     }
     // and "%61" with "=";
     len = strlen(str);
     for (p = str; (p = strstr(p, "\%61")); ++p) {
         memmove(p + 1, p + 3, len - (p - str) + 1);
         memcpy(p, "=", 1);
     }
     return strlen(str);
 }
spi_flash_size()
ICACHE_FLASH_ATTR size_t spi_flash_size ()
Definition at line 323 of file utils.c.
References spi_flash_get_id().
                         {                   // returns the flash chip's size, in BYTES
     uint32_t id = spi_flash_get_id();
     uint8_t manufacturer_id = id & 0xff;
 //  uint8_t type_id = (id >> 8) & 0xff;     // not relevant for size calculation
     uint8_t size_id = (id >> 16) & 0xff;    // lucky for us, WinBond ID's their chips as a form that lets us calculate the size
     if (manufacturer_id == 0xef) {
         return 1 << size_id;
     }
     else if (manufacturer_id == 0xe0) {     // LG Semi (Goldstar)
         return 1 << size_id;
     }
 //  else if (manufacturer_id == 0x1c) {     // Mitsubishi
 //      return 1 << size_id;
 //  }
     else {
         // could not identify chip
         return 0;
     }
 }
system_restart_defered()
ICACHE_FLASH_ATTR void system_restart_defered ()
Definition at line 352 of file utils.c.
References captdnsStop(), cron_destroy(), destroy_unix_time(), ETS_UART_INTR_DISABLE, httpdStop(), led_destroy(), NULL, NULL_MODE, os_timer_arm, os_timer_disarm, os_timer_setfn, printf, set_my_auto_connect(), stop_watchdog(), system_restart_defered_timer, system_restart_defered_timer_func(), wifi_destroy(), wifi_set_opmode_current(), and wifi_station_disconnect().
Referenced by mqtt_rpc_restart(), and resetTimerCb().
{
     httpdStop();        // stop http configuration server
     captdnsStop();      // stop captive dns
     wifi_destroy();
     set_my_auto_connect(false);
     wifi_station_disconnect();
     wifi_set_opmode_current(NULL_MODE);
     led_destroy();  // stop led blinking timers if its running
 #ifndef IMPULSE
 #ifndef NO_CRON
     cron_destroy();
 #endif  // NO_CRON
 #endif  // IMPULSE
     destroy_unix_time();
     stop_watchdog();
     ETS_UART_INTR_DISABLE();
     os_timer_disarm(&system_restart_defered_timer);
     os_timer_setfn(&system_restart_defered_timer, system_restart_defered_timer_func, NULL);
     os_timer_arm(&system_restart_defered_timer, 16000, 0);
 #ifdef DEBUG
     printf("going to restart in 16 sec...\n\r");
 #endif
 }
system_restart_defered_timer_func()
ICACHE_FLASH_ATTR static void system_restart_defered_timer_func (void * arg) static
Definition at line 343 of file utils.c.
References ICACHE_FLASH_ATTR, os_timer_disarm, printf, system_restart(), and system_restart_defered_timer.
Referenced by system_restart_defered().
{
     os_timer_disarm(&system_restart_defered_timer);
     system_restart();
 #ifdef DEBUG
     printf("...restarting now\n\r");
 #endif
 }
w_to_kw_str()
ICACHE_FLASH_ATTR void w_to_kw_str (char * w, char * kw)
Definition at line 191 of file utils.c.
References divide_str_by_1000().
{
     // just a wrapper
     divide_str_by_1000(w, kw);
 }
Variable Documentation
ccit_crc16_table
const uint16_t ccit_crc16_table[256]
Definition at line 27 of file utils.c.
system_restart_defered_timer
os_timer_t system_restart_defered_timer static
Definition at line 18 of file utils.c.
Referenced by system_restart_defered(), and system_restart_defered_timer_func().