MeterLogger: user/watchdog.c File Reference
watchdog.c File Reference
#include <esp8266.h>
#include "driver/gpio16.h"
#include "watchdog.h"
#include "unix_time.h"
#include "wifi.h"
#include "config.h"
#include "led.h"
#include "debug.h"
Data Structures
struct watchdog_t
Functions
ICACHE_FLASH_ATTR static void ext_watchdog_timer_func (void *arg)
ICACHE_FLASH_ATTR static void wifi_reconnect_timer_func (void *arg)
ICACHE_FLASH_ATTR static void watchdog_timer_func (void *arg)
ICACHE_FLASH_ATTR void init_watchdog ()
ICACHE_FLASH_ATTR void start_watchdog ()
ICACHE_FLASH_ATTR void stop_watchdog ()
ICACHE_FLASH_ATTR bool add_watchdog (uint32_t id, watchdog_type_t type, uint32_t timeout)
ICACHE_FLASH_ATTR bool remove_watchdog (uint32_t id)
ICACHE_FLASH_ATTR void reset_watchdog (uint32_t id)
Variables
static os_timer_t watchdog_timer
static os_timer_t ext_watchdog_timer
static os_timer_t wifi_reconnect_timer
watchdog_t watchdog_list [WATCHDOG_MAX]
volatile uint8_t watchdog_list_len
Function Documentation
add_watchdog()
ICACHE_FLASH_ATTR bool add_watchdog (uint32_t id, watchdog_type_t type, uint32_t timeout)
Definition at line 155 of file watchdog.c.
References get_uptime(), watchdog_t::id, watchdog_t::last_reset, os_printf, watchdog_t::timeout, watchdog_t::type, watchdog_list_len, and WATCHDOG_MAX.
{
     if (watchdog_list_len < WATCHDOG_MAX) {
 #ifdef DEBUG
         os_printf("add watchdog, id: %d\n", id);
 #endif
         watchdog_list[watchdog_list_len].id = id;
         watchdog_list[watchdog_list_len].type = type;
         watchdog_list[watchdog_list_len].timeout = timeout;
         watchdog_list[watchdog_list_len].last_reset = get_uptime();
         watchdog_list_len++;
         return true;
     }
     else {
 #ifdef DEBUG
         os_printf("watchdog error, cant add more\n");
 #endif
         return false;
     }
 }
ext_watchdog_timer_func()
ICACHE_FLASH_ATTR static void ext_watchdog_timer_func (void * arg) static
Definition at line 25 of file watchdog.c.
References gpio16_input_get(), and gpio16_output_set().
Referenced by start_watchdog().
{
     if (gpio16_input_get()) {
         gpio16_output_set(0);
     }
     else {
         gpio16_output_set(1);
     }
 }
init_watchdog()
ICACHE_FLASH_ATTR void init_watchdog ()
Definition at line 125 of file watchdog.c.
References memset, and watchdog_list_len.
{
     memset(watchdog_list, 0x00, sizeof(watchdog_list));
     watchdog_list_len = 0;
 }
remove_watchdog()
ICACHE_FLASH_ATTR bool remove_watchdog (uint32_t id)
Definition at line 175 of file watchdog.c.
References watchdog_t::id, NOT_ENABLED, os_printf, watchdog_t::timeout, watchdog_t::type, and watchdog_list_len.
{
     if (watchdog_list_len > 0) {
 #ifdef DEBUG
         os_printf("remove watchdog, id: %d\n", id);
 #endif
         watchdog_list[watchdog_list_len].id = 0;
         watchdog_list[watchdog_list_len].type = NOT_ENABLED;
         watchdog_list[watchdog_list_len].timeout = 0;
         watchdog_list_len--;
         return true;
     }
     else {
 #ifdef DEBUG
         os_printf("watchdog error, cant remove %d\n", id);
 #endif
         return false;
     }
 }
reset_watchdog()
ICACHE_FLASH_ATTR void reset_watchdog (uint32_t id)
Definition at line 194 of file watchdog.c.
References get_uptime(), watchdog_t::last_reset, os_printf, and WATCHDOG_MAX.
{
     uint32_t i;
 #ifdef DEBUG
     os_printf("reset watchdog, id: %d\n", id);
 #endif
     for (i = 0; i < WATCHDOG_MAX; i++) {
         if (watchdog_list[i].id == id) {
             watchdog_list[i].last_reset = get_uptime();
         }
     }
 }
start_watchdog()
ICACHE_FLASH_ATTR void start_watchdog ()
Definition at line 130 of file watchdog.c.
References ext_watchdog_timer, ext_watchdog_timer_func(), gpio16_output_conf(), gpio16_output_set(), NULL, os_printf, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, watchdog_timer, and watchdog_timer_func().
{
 #ifdef DEBUG
     os_printf("watchdog started\n");
 #endif
     // start configurable software watchdog system
     os_timer_disarm(&watchdog_timer);
     os_timer_setfn(&watchdog_timer, (os_timer_func_t *)watchdog_timer_func, NULL);
     os_timer_arm(&watchdog_timer, 1000, 1);
     // start extern watchdog timer  (MCP1316)
     os_timer_disarm(&ext_watchdog_timer);
     os_timer_setfn(&ext_watchdog_timer, (os_timer_func_t *)ext_watchdog_timer_func, NULL);
     os_timer_arm(&ext_watchdog_timer, 1000, 1);
     //Set GPIO16 to output mode
     gpio16_output_conf();
     gpio16_output_set(1);
 }
stop_watchdog()
ICACHE_FLASH_ATTR void stop_watchdog ()
Definition at line 148 of file watchdog.c.
References ext_watchdog_timer, os_printf, and os_timer_disarm.
{
 #ifdef DEBUG
     os_printf("watchdog stopped\n");
 #endif
     os_timer_disarm(&ext_watchdog_timer);
 }
watchdog_timer_func()
ICACHE_FLASH_ATTR static void watchdog_timer_func (void * arg) static
Definition at line 72 of file watchdog.c.
References ext_watchdog_timer, get_uptime(), watchdog_t::last_reset, led_pattern_b(), NETWORK_RESTART, NETWORK_RESTART_DELAY, NOT_ENABLED, NULL, NULL_MODE, os_printf, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, REBOOT, REBOOT_VIA_EXT_WD, set_my_auto_connect(), system_restart(), WATCHDOG_MAX, wifi_reconnect_timer, wifi_reconnect_timer_func(), wifi_set_opmode_current(), wifi_station_disconnect(), and wifi_stop_scan().
Referenced by start_watchdog().
{
     uint32_t i;
     uint32_t uptime;
     uptime = get_uptime();
 //  if (uptime) {   // only run watchdog if we have unix time
     for (i = 0; i < WATCHDOG_MAX; i++) {
         if ((watchdog_list[i].type != NOT_ENABLED) &&
             (watchdog_list[i].last_reset) &&
             ((int32_t)watchdog_list[i].last_reset < (int32_t)(uptime - watchdog_list[i].timeout))) {
 #ifdef DEBUG
             os_printf("watchdog timeout, id: %d\n", watchdog_list[i].id);
 #endif
             switch (watchdog_list[i].type) {
                 case REBOOT:
                     system_restart();
 #ifdef DEBUG
                     os_printf("reboot\n");
 #endif
                     break;
                 case NETWORK_RESTART:
                     // DEBUG: hack to get it to reconnect on weak wifi
                     // force reconnect to wireless
                     led_pattern_b();    // DEBUG to se if we ever try to restart network
                     wifi_stop_scan();
                     set_my_auto_connect(false);
                     wifi_station_disconnect();
                     wifi_set_opmode_current(NULL_MODE);
 #ifdef DEBUG
                     os_printf("stopped wifi and wifi scanner\n");
 #endif
                     // and (re)-connect when last wifi scan is done - wait 6 second before starting
                     os_timer_disarm(&wifi_reconnect_timer);
                     os_timer_setfn(&wifi_reconnect_timer, (os_timer_func_t *)wifi_reconnect_timer_func, NULL);
                     os_timer_arm(&wifi_reconnect_timer, NETWORK_RESTART_DELAY, 0);
 #ifdef DEBUG
                     os_printf("scheduled wifi for restart...\n");
 #endif
                     break;
                 case REBOOT_VIA_EXT_WD:
                     os_timer_disarm(&ext_watchdog_timer);
 #ifdef DEBUG
                     os_printf("reboot via ext watchdog\n");
 #endif
                     break;
             }
             watchdog_list[i].last_reset = get_uptime();
         }
     }
 }
wifi_reconnect_timer_func()
ICACHE_FLASH_ATTR static void wifi_reconnect_timer_func (void * arg) static
Definition at line 34 of file watchdog.c.
References syscfg_t::ap_enabled, led_stop_pattern(), NULL, os_printf, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, set_my_auto_connect(), STATION_MODE, STATIONAP_MODE, sys_cfg, wifi_get_opmode(), wifi_reconnect_timer, wifi_scan_is_running(), wifi_set_opmode_current(), wifi_start_scan(), and wifi_station_connect().
Referenced by watchdog_timer_func().
{
     if (wifi_scan_is_running()) {
         // reschedule if wifi scan is running
         os_timer_disarm(&wifi_reconnect_timer);
         os_timer_setfn(&wifi_reconnect_timer, (os_timer_func_t *)wifi_reconnect_timer_func, NULL);
         os_timer_arm(&wifi_reconnect_timer, 1000, 0);
 #ifdef DEBUG
         os_printf("scanner still running - rescheduling reccont\n");
 #endif
     }
     else {
         os_timer_disarm(&wifi_reconnect_timer);
 #ifdef AP
         if (sys_cfg.ap_enabled) {
             if (wifi_get_opmode() != STATIONAP_MODE) {
                 wifi_set_opmode_current(STATIONAP_MODE);
             }
         }
         else {
             if (wifi_get_opmode() != STATION_MODE) {
                 wifi_set_opmode_current(STATION_MODE);
             }
         }
 #else
         if (wifi_get_opmode() != STATION_MODE) {
             wifi_set_opmode_current(STATION_MODE);
         }
 #endif  // AP
         led_stop_pattern(); // DEBUG
         set_my_auto_connect(true);
         wifi_station_connect();
         wifi_start_scan();
 #ifdef DEBUG
         os_printf("watchdog restarted wifi and started wifi scanner\n");
 #endif
     }
 }
Variable Documentation
ext_watchdog_timer
os_timer_t ext_watchdog_timer static
Definition at line 12 of file watchdog.c.
Referenced by start_watchdog(), stop_watchdog(), and watchdog_timer_func().
watchdog_list
watchdog_t watchdog_list[WATCHDOG_MAX]
Definition at line 22 of file watchdog.c.
watchdog_list_len
volatile uint8_t watchdog_list_len
Definition at line 23 of file watchdog.c.
Referenced by add_watchdog(), init_watchdog(), and remove_watchdog().
watchdog_timer
os_timer_t watchdog_timer static
Definition at line 11 of file watchdog.c.
Referenced by start_watchdog().
wifi_reconnect_timer
os_timer_t wifi_reconnect_timer static
Definition at line 13 of file watchdog.c.
Referenced by watchdog_timer_func(), and wifi_reconnect_timer_func().