MeterLogger: user/watchdog.h File Reference
watchdog.h File Reference
Macros
#define WATCHDOG_MAX 1
#define MQTT_WATCHDOG_ID 1
#define MQTT_WATCHDOG_TIMEOUT 120
#define NETWORK_RESTART_DELAY 6000
Enumerations
enum watchdog_type_t { NOT_ENABLED, REBOOT, REBOOT_VIA_EXT_WD, NETWORK_RESTART }
Functions
ICACHE_FLASH_ATTR void init_watchdog ()
ICACHE_FLASH_ATTR void start_watchdog ()
ICACHE_FLASH_ATTR void stop_watchdog ()
ICACHE_FLASH_ATTR bool add_watchdog (uint32_t id, watchdog_type_t type, uint32_t timeout)
ICACHE_FLASH_ATTR bool remove_watchdog (uint32_t id)
ICACHE_FLASH_ATTR void reset_watchdog (uint32_t id)
Macro Definition Documentation
MQTT_WATCHDOG_ID
#define MQTT_WATCHDOG_ID 1
Definition at line 3 of file watchdog.h.
MQTT_WATCHDOG_TIMEOUT
#define MQTT_WATCHDOG_TIMEOUT 120
Definition at line 4 of file watchdog.h.
NETWORK_RESTART_DELAY
#define NETWORK_RESTART_DELAY 6000
Definition at line 6 of file watchdog.h.
Referenced by watchdog_timer_func().
WATCHDOG_MAX
#define WATCHDOG_MAX 1
Definition at line 1 of file watchdog.h.
Referenced by add_watchdog(), reset_watchdog(), and watchdog_timer_func().
Enumeration Type Documentation
watchdog_type_t
enum watchdog_type_t
Enumerator
NOT_ENABLED
REBOOT
REBOOT_VIA_EXT_WD
NETWORK_RESTART
Definition at line 8 of file watchdog.h.
              {
     NOT_ENABLED,
     REBOOT,
     REBOOT_VIA_EXT_WD,
     NETWORK_RESTART
 } watchdog_type_t;
Function Documentation
add_watchdog()
ICACHE_FLASH_ATTR bool add_watchdog (uint32_t id, watchdog_type_t type, uint32_t timeout)
Definition at line 155 of file watchdog.c.
References get_uptime(), watchdog_t::id, watchdog_t::last_reset, os_printf, watchdog_t::timeout, watchdog_t::type, watchdog_list_len, and WATCHDOG_MAX.
{
     if (watchdog_list_len < WATCHDOG_MAX) {
 #ifdef DEBUG
         os_printf("add watchdog, id: %d\n", id);
 #endif
         watchdog_list[watchdog_list_len].id = id;
         watchdog_list[watchdog_list_len].type = type;
         watchdog_list[watchdog_list_len].timeout = timeout;
         watchdog_list[watchdog_list_len].last_reset = get_uptime();
         watchdog_list_len++;
         return true;
     }
     else {
 #ifdef DEBUG
         os_printf("watchdog error, cant add more\n");
 #endif
         return false;
     }
 }
init_watchdog()
ICACHE_FLASH_ATTR void init_watchdog ()
Definition at line 125 of file watchdog.c.
References memset, and watchdog_list_len.
{
     memset(watchdog_list, 0x00, sizeof(watchdog_list));
     watchdog_list_len = 0;
 }
remove_watchdog()
ICACHE_FLASH_ATTR bool remove_watchdog (uint32_t id)
Definition at line 175 of file watchdog.c.
References watchdog_t::id, NOT_ENABLED, os_printf, watchdog_t::timeout, watchdog_t::type, and watchdog_list_len.
{
     if (watchdog_list_len > 0) {
 #ifdef DEBUG
         os_printf("remove watchdog, id: %d\n", id);
 #endif
         watchdog_list[watchdog_list_len].id = 0;
         watchdog_list[watchdog_list_len].type = NOT_ENABLED;
         watchdog_list[watchdog_list_len].timeout = 0;
         watchdog_list_len--;
         return true;
     }
     else {
 #ifdef DEBUG
         os_printf("watchdog error, cant remove %d\n", id);
 #endif
         return false;
     }
 }
reset_watchdog()
ICACHE_FLASH_ATTR void reset_watchdog (uint32_t id)
Definition at line 194 of file watchdog.c.
References get_uptime(), watchdog_t::last_reset, os_printf, and WATCHDOG_MAX.
{
     uint32_t i;
 #ifdef DEBUG
     os_printf("reset watchdog, id: %d\n", id);
 #endif
     for (i = 0; i < WATCHDOG_MAX; i++) {
         if (watchdog_list[i].id == id) {
             watchdog_list[i].last_reset = get_uptime();
         }
     }
 }
start_watchdog()
ICACHE_FLASH_ATTR void start_watchdog ()
Definition at line 130 of file watchdog.c.
References ext_watchdog_timer, ext_watchdog_timer_func(), gpio16_output_conf(), gpio16_output_set(), NULL, os_printf, os_timer_arm, os_timer_disarm, os_timer_func_t, os_timer_setfn, watchdog_timer, and watchdog_timer_func().
{
 #ifdef DEBUG
     os_printf("watchdog started\n");
 #endif
     // start configurable software watchdog system
     os_timer_disarm(&watchdog_timer);
     os_timer_setfn(&watchdog_timer, (os_timer_func_t *)watchdog_timer_func, NULL);
     os_timer_arm(&watchdog_timer, 1000, 1);
     // start extern watchdog timer  (MCP1316)
     os_timer_disarm(&ext_watchdog_timer);
     os_timer_setfn(&ext_watchdog_timer, (os_timer_func_t *)ext_watchdog_timer_func, NULL);
     os_timer_arm(&ext_watchdog_timer, 1000, 1);
     //Set GPIO16 to output mode
     gpio16_output_conf();
     gpio16_output_set(1);
 }
stop_watchdog()
ICACHE_FLASH_ATTR void stop_watchdog ()
Definition at line 148 of file watchdog.c.
References ext_watchdog_timer, os_printf, and os_timer_disarm.
{
 #ifdef DEBUG
     os_printf("watchdog stopped\n");
 #endif
     os_timer_disarm(&ext_watchdog_timer);
 }